### ISSUE TITLE
Issue sending trade offers with many items.

### ISSUE THREAD

**Issue by graycatfromspace** [Alex7Kom/node-steam-tradeoffers#100]
Hello, I am currently having an issues sending trade offers. The offer will send completely fine but once i open the offer the items have blank squares between them. When you try to accept I get error (2). The funny part is that I made another script that just takes the whole inventory of the bot and sends it and that works flawlessly. Only when trying to pick certain items and send it causes this issue the code used is below.

    //produce array from items to send the winner
    offers.loadMyInventory({
      appId: 730,
      contextId: 2
    }, function(err, items) {
      var invitem;
      var bountyitem;

      var items2send = [];
      var itemssent = 0;

      //console.log("\nAttempting to send "+msg.bounty.itemlist.length+" items to "+msg.steam64+" worth $"+msg.bounty.total);

      //for each item in bot inventory check if its one to be sent
      for(var i = 0; i < items.length; i++){
        item = items[i];

        for(var r = 0; r < msg.bounty.itemlist.length; r++){
          bountyitem = msg.bounty.itemlist[r];

          if(item.classid == bountyitem.classid){
            var itemarray = {
              appid: 730,
              contextid: 2,
              amount: 1,
              assetid: item.id
            };

            items2send.push(itemarray);
            itemssent++;
          };
        }
      } 

      //check if any items actually are ready to be sent
      if(itemssent > 0){

          //make the trade offer
          offers.makeOffer ({
            partnerSteamId: msg.steam64,
            accessToken: info.tradetoken,
            itemsFromMe: items2send,
            itemsFromThem: [],
            message: 'Congradulations! You won bounty: '+msg.bounty.id
          }, function(err, response){
            if (err) {
              throw err;
            }
            console.log("\nWinner's TradeOffer sent to "+msg.steam64);
          });

      } else {
        console.log(msg.bounty.itemlist.length+" Items not found!");
        for(var z = 0; z < msg.bounty.itemlist.length; z++){
          var bountyitem = msg.bounty.itemlist[z];
          console.log("-["+bountyitem.classid+"]"+bountyitem.market_name);
        };
      }

    });

**Comment by srabouin** [comment]
You're probably trying to send the same item multiple times. Keep track of items you've already added.

**Comment by graycatfromspace** [comment]
*facepalm* Ill give that a try, why didn't I think of that >.<

**Comment by graycatfromspace** [comment]
working great now thanks for that, still kinda mad at myself for not thinking of it.
