### ISSUE TITLE
array for itemsFromMe

### ISSUE THREAD

**Issue by ReDFoX43rus** [Alex7Kom/node-steam-tradeoffers#101]
I made smth like

        var len = itemsID.length;
	var itemsFromMeArr = [];
	for(var i = 0; i < len; i++)
	{
		itemsFromMeArr.push({
			appid: 730,
			contextid: 2,
			assetid: parseInt(itemsID[i])
		});
	}
	
	console.log(itemsFromMeArr);
	
	offers.makeOffer({
		partnerSteamId: steamID.toString(),
        itemsFromMe: itemsFromMeArr,
        itemsFromThem: [],
        message: 'This is test'
	}, function(err, response) {
		if(err)
			throw err;
		console.log(response);
	});

But it doesnt work

ERR: Error: There was an error sending your trade offer.  Please try again later. (26)

What went wrong?

**Comment by srabouin** [comment]
Don't parseInt itemsid, it is a string for a reason

**Comment by ReDFoX43rus** [comment]
Im sorry for this silly issue.
This code works. The problem was that itemsFromMeArr was empty
Sorry

**Comment by frook1** [comment]
I have the same issue. I can receive offers but can't send. My code look like this:

var admin = "76561134992416488";
User.findOne({openid:offer.steamid_other}, function(err, docs) {
    console.log("MakeOffer");
    offers.makeOffer({
        partnerSteamId: admin,
        itemsFromMe: [{
            appid: 730,
            contextid: 2,
            assetid: docs.offer.items_to_receive[0].assetid
        }],
        itemsFromThem: [],
        message: 'Test'
    }, function(callback) {
        console.log("MakeOffer callback");
        console.log(callback);
    });
});

Anybody can help me?

**Comment by ReDFoX43rus** [comment]
assetid might be empty (like was mine)
