### ISSUE TITLE
storehouse.js example dont working

### ISSUE THREAD

**Issue by Yashko** [Alex7Kom/node-steam-tradeoffers#102]
I using code from storehouse.js example, and my bot dont accepting trade offers.
How i can fix it?

**Comment by Yashko** [comment]
![3d248c6cfc5b3a5c3a94cf6d683b8a79](https://cloud.githubusercontent.com/assets/4582615/7511036/9e2f37e8-f4aa-11e4-886c-e9584dc9f964.png)

**Comment by Kuba77** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd

Your sessionid most likely expired.

**Comment by Yashko** [comment]
Looks like ;c
thanks
