### ISSUE TITLE
It's possible to set a timeout option to an offer?

### ISSUE THREAD

**Issue by Commanche2** [Alex7Kom/node-steam-tradeoffers#106]
As I can see at Steam API there is an option to set a timeout to an offer (*expiration_time*) https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#CEcon_TradeOffer

I was looking for it in this Node API but, maybe im blind, I don't find any kind of option to do that. It's possible to set this option (*expiration_time*) in *makeOffer* function, or is nowadays unimplemented?

**Comment by scholtzm** [comment]
I don't think you can set expiration date when sending the trade offer.

The trade offer object you linked is for `GetTradeOffers` and `GetTradeOffer` API methods described on the same page and doesn't necessarily apply to `makeOffer` function in this lib.

**Comment by Commanche2** [comment]
There is any way to do same like what I'm telling? If the offer surpass a determined time, it must cancel, to avoid have a lot of pending offers.

**Comment by Larrdawg** [comment]
I would suggest using a setTimeout after the trade is placed, and cancelling the trade in the setTimeout function. setTimeout is also aSync so you can have multiple running.

**Comment by Commanche2** [comment]
Thank you so mutch. I'll try it.
