### ISSUE TITLE
[Error: There was an error sending your trade offer.  Please try again later. (26)]

### ISSUE THREAD

**Issue by frook1** [Alex7Kom/node-steam-tradeoffers#107]
Hello,
I can receive offers but can't send. My code look like this:
```javascript
var admin = "76561134992416488";
User.findOne({openid:offer.steamid_other}, function(err, docs) {
    console.log("MakeOffer");
    offers.makeOffer({
        partnerSteamId: admin,
        itemsFromMe: [{
            appid: 730,
            contextid: 2,
            assetid: docs.offer.items_to_receive[0].assetid
        }],
        itemsFromThem: [],
        message: 'Test'
    }, function(callback) {
        console.log("MakeOffer callback");
        console.log(callback);
    });
});
````

[Error: There was an error sending your trade offer.  Please try again later. (26)]

![aaa](https://cloud.githubusercontent.com/assets/12482834/7670432/6bedb7ee-fca4-11e4-82c8-96044bc55bf8.jpg)

Anybody can help me?

**Comment by scholtzm** [comment]
Convert `assetid` into string.

**Comment by frook1** [comment]
assetid is a string

UPDATE:
```javascript
    User.findOne({openid:offer.steamid_other}, function(err, docs) {
        var OfferObj = {
            partnerSteamId: "76561197992416988",//offer.steamid_other,
            //partnerAccountId: "214112667",
            accessToken: "WOxNQkib",
            itemsFromMe: [{
                appid: 730,
                contextid: 2,
                assetid: String(docs.offer.items_to_receive[0].assetid)
            }],
            itemsFromThem: [],
            message: 'Test message'
        };
        offers.makeOffer(OfferObj, function(callback) {
            logger.info("MakeOffer callback");
            console.log(callback);
            console.log(OfferObj);
        });
    });
```

OUTPUT:
![code1](https://cloud.githubusercontent.com/assets/12482834/7672252/9fb2625e-fceb-11e4-88f2-d63141b85c76.jpg)

**Comment by srabouin** [comment]
Are you sure you still have this item in your inventory?
I think itemsFromMe usually has amount:1 on each item too, never really tested if it works without.

**Comment by Zatnar** [comment]
Try replacing the contextid: 2, by contextid: "2", it fixed the error for me I think.

**Comment by vejbuch** [comment]
Hello,
I have the same problem. This is my code. Please advice, thank you.

        if (steam.on) {
          offers.makeOffer ({
            partnerSteamId: admin,
            itemsFromMe: [],
            itemsFromThem: [
              {
                appid: 730,
                contextid: 2,
                amount: 1,
                assetid: 527644929
              }            
            ],
            message: 'This is test'
          }, function(err, response){
            if (err) {
              throw err;
            }
            console.log(response);
          });
        }
    }); 



Error: There was an error sending your trade offer.  Please try again later. (26
)
    at SteamTradeOffers.<anonymous> (C:\Users\Vejbuch\node_modules\steam-tradeof
fers\index.js:430:18)
    at Request.self.callback (C:\Users\Vejbuch\node_modules\steam-tradeoffers\no
de_modules\request\request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Vejbuch\node_modules\steam-tradeoffers\node
_modules\request\request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Vejbuch\node_modules\steam-tradeoff
ers\node_modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by srabouin** [comment]
26 usually means you're trying to offer an item you don't have anymore

**Comment by vejbuch** [comment]
hmm, assitId is a classid from steam json?

**Comment by scholtzm** [comment]
`assetid` is `id`.
