### ISSUE TITLE
quit bot "after all is done"

### ISSUE THREAD

**Issue by eXoCoding** [Alex7Kom/node-steam-tradeoffers#109]
after using offers.makeOffer it takes some seconds until the trade is really created in steam and i get the response. i have the problem, that if i create an offer and want to quit the bot using process.exit(0), it dosn't create the offer. and i dont want to use unclean settimeout-methods. so thats my querstion: how can i quit the bot "after all is done".

Some lines:

setInterval(function(){
	console.log("Tick");
	SendOffers(1, function(err){	//send tradingoffer, update set tradeid="TheTradeID"
		if(err) throw err;
	});

	CheckTrades(1, function(err){	//get offer.trade_offer_state, if offer declined set resuld="-1"
		if(err) throw err;
	});
	
	connection.query('SELECT * from donation_open_offers where result=0', function(err, rows, fields) {
		if(rows.length == 0) process.exit(0);
	});
}, 5000);

**Comment by scholtzm** [comment]
Use the callback?

**Comment by eXoCoding** [comment]
you mean an process.exit in the callback from offers.makeOffer, but what if i use makeOffer more times in a row?

**Comment by scholtzm** [comment]
Either write your own logic or use [caolan/async](https://github.com/caolan/async).

**Comment by eXoCoding** [comment]
why isnt this working

var BLOCK=0;

var GetState = function(tradeid, callback){
	request({
		url: "https://api.steampowered.com/IEconService/GetTradeOffer/v001/?key=2B09E0E813A2CDABE5459AA28484B00F&tradeofferid=" + tradeid
	}, function (error, resp, body) {
		if (!error && resp.statusCode === 200) {
			callback(null, JSON.parse(body));
		}
	});						
}

var SendOffer = function(data, callback){
	BLOCK=1;
	bot.on('webSessionID', function(sessionID) {
		bot.webLogOn(function(newCookie){
			offers.setup({
				sessionID: sessionID,
				webCookie: newCookie
			}, function(err) {
				if (err) throw err;
				var items=data.items;
				items=items.split(" ");
				var list=[];
				for (var j = 0; j < items.length; ++j) {
					if(items[j] != "")
						list.push(JSON.parse('{"appid":730,"contextid":2,"amount":1,"assetid": "'+ items[j] +'" }'));
				}
				offers.makeOffer ({
					partnerSteamId: data.steamid,
					accessToken: data.accessToken,
					itemsFromThem: list,
					itemsFromMe: [],
					message: 'Vielen Dank für dein Interesse und deinem Betrag an Skilltech. Deine Gutschrift: ' + data.wert + '€. !! Security Token: ' + data.pin + ' !!'
				}, function(err, response){
					BLOCK=0;
					//needs about 10 seconds to callback, until bot logged in, offers created and send
					if (! err){
						connection.query('update donation_open_offers set tradeid="' + response.tradeofferid + '" where steamid="' + data.steamid +'" and timestamp="' + data.timestamp + '"', function(err, data, fields) {
							if(err) throw err;
						});
						callback("CREATED", response.tradeofferid);
					} else {
						callback("FAILED", "");
					}
				});
			});
		});
	});
}


var SendOffers = function(botid, callback){
	connection.query('SELECT * from donation_open_offers where botid="'+ botid +'" and tradeid=""', function(err, rows, fields) {
		if(err) throw err;
		var i=0;
		while(rows[i]){
			SendOffer(rows[i], function(status, tradeid){	//need wait
				console.log(status + " " + tradeid);
			});
			i++;
		}
	});
	callback(null);
}

var DeleteOffer = function(tradeid, callback){
	BLOCK=1;
	bot.on('webSessionID', function(sessionID) {
		bot.webLogOn(function(newCookie){
			offers.setup({
				sessionID: sessionID,
				webCookie: newCookie
			}, function(err) {
				if (err) throw err;
				offers.cancelOffer({tradeOfferId: tradeid}, function(err){
					//needs about 10 seconds to callback, end delete offer
					if(err) throw err;
					connection.query('update donation_open_offers set result="-1" where tradeid="'+ tradeid +'"', function(err, rows, fields) {
						if(err) throw err;
					});
					console.log("CANCELED " + tradeid);
					BLOCK=0;
					callback(null);
				});
			});
		});
	});
}

var SuccessOffer = function(tradeid, callback){
	console.log("SUCCESS " + tradeid);
	connection.query('update donation_open_offers set result="1" where tradeid="' + tradeid + '"', function(err, rows, fields) {
		if(err) throw err;
	});
	connection.query('select * from donation_open_offers where tradeid="' + tradeid + '"', function(err, rows, fields) {
		connection.query('update userdata set guthaben=guthaben+'+ rows[0].wert +' where steamid="' +rows[0].steamid+'"', function(err, rows, fields) {
			if(err) throw err;
		});
	});
	callback(null);
}

var CheckTrade = function(data, callback){
	var time = Math.floor(new Date() / 1000);
	data.timestamp=data.timestamp + 5*60;
	if(data.timestamp <= time){
		GetState(data.tradeid, function(err, response){
			var tradeid = response.response.offer.tradeofferid;
			if(3 == response.response.offer.trade_offer_state){
				SuccessOffer(tradeid, function(err){
					if(err) throw err;
				});	
			} else {
				DeleteOffer(tradeid, function(err){
					if(err) throw err;
				});			
			}
		});
	} else {
		GetState(data.tradeid, function(err, response){
			var tradeid = response.response.offer.tradeofferid;
			if(response.response.offer.trade_offer_state == 3){
				SuccessOffer(tradeid, function(err){
					if(err) throw err;
				});	
			} else {
				if(response.response.offer.trade_offer_state == 1 || response.response.offer.trade_offer_state == 4 || response.response.offer.trade_offer_state == 7 || response.response.offer.trade_offer_state == 8 || response.response.offer.trade_offer_state == 10){
					DeleteOffer(tradeid, function(err){
						if(err) throw err;
					});	
				} else {
					console.log("UNKNOWN " + tradeid);
				}
			}
		});
	}
}

var CheckTrades = function(botid, callback){
	connection.query('SELECT * from donation_open_offers where botid="'+ botid +'" and tradeid!="" and result=0', function(err, rows, fields) {
		if(err) throw err;
		var i=0;
		while(rows[i]){
			CheckTrade(rows[i], function(err){
				if(err) throw err;
			});
			i++;
		}
	});
	callback(null);
}

function TICK(){
	console.log('EXEC');
	SendOffers(1, function(err){	//send tradingoffer, update set tradeid="TheTradeID"
		if(err) throw err;
	});

	CheckTrades(1, function(err){	//get offer.trade_offer_state, if offer declined set resuld="-1"
		if(err) throw err;
	});
}

// TICK(); //Then it works 1 time and dond process.exit();

/*
TICK();				//process will exit to fast, not all callbacks recieved -> no trade
process.exit(0);
*/

/*
TICK();
setTimeout(function(){
	process.exit(0)
},40000);	//this will work, but unsave
*/

setInterval(function(){
	if(! BLOCK){
		TICK();		//nothing happends and Block is allways 1
	} else {
		console.log('WAIT');
	}
	connection.query('SELECT * from donation_open_offers where result=0', function(err, rows, fields) {
		if(rows.length == 0) process.exit(0);
	});
}, 5000);

**Comment by eXoCoding** [comment]
i wote my own logic with set and unset variables. Thx to you scholtzm for helping :+1:
