### ISSUE TITLE
Verifying a trade was successful

### ISSUE THREAD

**Issue by AardvarkMike** [Alex7Kom/node-steam-tradeoffers#111]
Is it possible to verify whether a trade was successful?

I thought about perhaps checking the tradeoffer against .loadMyInventory() afterwards, however there is no common unique Id. The trade offer seems to have an assetid that seems unique, and the inventory listing just an 'id' but they are not common. 

Classid and InstanceId may be sufficient for skins, but for keys etc. they are identical.

Any suggestions?

**Comment by MrXromik** [comment]
Also interested in how to check the exchange confirmed

**Comment by BenWoodford** [comment]
The GetPlayerItems endpoint provides an original_id, which is unique for each instance of an item. Unfortunately, that endpoint is _very_ unreliable I find. I'm logging original IDs where possible when users do a trade and only 20-30% of trades seem to successfully retrieve the original ID from that endpoint.

Class and Instance ID put together are unique for an item in an inventory, and change as soon as it moves hands. It's incredibly annoying, especially as trades will go to state 8 if the item is removed from the destination inventory at any point.

**Comment by srabouin** [comment]
https://steamcommunity.com/trade/' + tradeid + '/receipt/

tradeid is received in the callback when you accept an offer with acceptOffer. You'll get the current id's with this, so you don't to bother with GetPlayerItems to get original ids or do all sorts of useless shit.

**Comment by BenWoodford** [comment]
What about offers initiated by the library? You can only get current status on it and sometimes that reports the ETradeOfferState as 8 if the recipient has moved the item out of their inventory before the library checks the status again.

**Comment by BenWoodford** [comment]
Just noticed [this](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/README.md#getitemsoptions-callback) on the docs.

If getItems() definitely returns the new IDs, that's brilliant and a great help.

**Comment by Alex7Kom** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/121
