### ISSUE TITLE
How to get asset ID

### ISSUE THREAD

**Issue by vejbuch** [Alex7Kom/node-steam-tradeoffers#114]
Hi,
how to get ASSETID from steam JSON ?

http://steamcommunity.com/profiles/ID/inventory/json/730/2

**Comment by vejbuch** [comment]
Or get assetid with classid?

**Comment by scholtzm** [comment]
Example:

```js
"3763834126": {
    "id": "3763834126",
    "classid": "2675",
    "instanceid": "11040547",
    "amount": "1",
    "pos": 1
}
```

In this case `id` is the `assetid` you are looking for.

**Comment by vejbuch** [comment]
Thnaks, but: 

            itemsFromThem: [
                          {
                appid: 730,
                contextid: 2,
                amount: 1,
                assetid: 2510256920
              }
   ],

{"2510256920":{"id":"2510256920","classid":"561861079","instanceid":"188530139","amount":"1","pos":1},"2509940707":

bot say error 26 :(

**Comment by vejbuch** [comment]
ok, if in "" :) thanks!!!
