### ISSUE TITLE
Quit bot, aftre send tradeoffer

### ISSUE THREAD

**Issue by vejbuch** [Alex7Kom/node-steam-tradeoffers#116]
Hi,
i need quit bot with send trade, but not quit script.

If say process.exit(1), kill the complet script.

Help me? :)
i USE https://gist.github.com/MStruntze/d7de3ea07b2777ca9f6d

<code>
var net = require('net');
var listenport = 3000; // Should be the same as in the php script
// Set up server
var Server = net.createServer(function(Sock) {
    console.log('Client Connected.'); 
    Sock.on('data', function(data) {
       console.log('Data received: ' + data);   
       dataobj = JSON.parse(data);  
       console.log('Item ID: ' + dataobj.itemid);
var admin = '76561197994630835'; // put your steamid here so the bot can send you trade offers
var logOnOptions = {
  accountName: '###########',
  password: '#############'
};
var authCode = ''; // code received by email
if (require('fs').existsSync('sentry')) {
  logOnOptions['shaSentryfile'] = require('fs').readFileSync('sentry');
} else if (authCode != '') {
  logOnOptions['authCode'] = authCode;
}

var Steam = require('steam');
var SteamTradeOffers = require('../'); // change to 'steam-tradeoffers' if not running from the examples subdirectory
var steam = new Steam.SteamClient();
var offers = new SteamTradeOffers();
steam.logOn(logOnOptions);
steam.on('debug', console.log);
steam.on('loggedOn', function(result) {
  console.log('Logged in!');
  console.log(admin);
  steam.setPersonaState(Steam.EPersonaState.Online);
});

steam.on('webSessionID', function(sessionID) {
  steam.webLogOn(function(newCookie){
    offers.setup({
      sessionID: sessionID,
      webCookie: newCookie
    }, function(err) {
      if (err) {
        throw err;
      }
      offers.loadMyInventory({
        appId: 730,
        contextId: 2
      }, function(err, items) {
        var item;
        // picking first tradable item
        for (var i = 0; i < items.length; i++) {
          if (items[i].tradable) {
            item = items[i];
            break;
          }
        }
        // if there is such an item, making an offer with it   2509940707
        if (item) {
          offers.makeOffer ({
            partnerSteamId: admin,
            itemsFromMe: [],
            itemsFromThem: [
                          {
                appid: 730,
                contextid: 2,
                amount: 1,
                assetid: "2510256920"
              }
            ],
            message: 'This is test'
          }, function(err, response){
            if (err) {
              throw err;
            }
            console.log(response);
            logOff()
          });
        }
      });
    });
  });
});
steam.on('sentry', function(data) {
  require('fs').writeFileSync('sentry', data);
});
    });
           Sock.on('end', function() {
        console.log('Client Disconnected.');
    });
    Sock.pipe(Sock);
});

Server.listen(listenport, function() {
   console.log('Listening on port ' + listenport); 
});
</code>

**Comment by scholtzm** [comment]
This is an issue tracker, not your personal helpdesk. You should ask here http://www.reddit.com/r/nodesteam or elsewhere.
