### ISSUE TITLE
Identify CS:GO item

### ISSUE THREAD

**Issue by Yashko** [Alex7Kom/node-steam-tradeoffers#117]
Hi, how i can identify unique cs:go item?
classid + instanceid not unique
thank you

**Comment by vejbuch** [comment]
assetid :)

https://github.com/Alex7Kom/node-steam-tradeoffers/issues/114

**Comment by Yashko** [comment]
I cant identify item by assetid because when i trade this item - assetid changes

**Comment by Alex7Kom** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/121
