### ISSUE TITLE
Error: Access Denied at SteamTradeOffers

### ISSUE THREAD

**Issue by balatsky** [Alex7Kom/node-steam-tradeoffers#118]
Error: Access Denied at SteamTradeOffers when I try to start storekeeper. Any ideas?
![screenshot_2](https://cloud.githubusercontent.com/assets/7093650/8006578/01cc7af4-0b9e-11e5-8398-4ed964bc153c.png)

**Comment by Alex7Kom** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/wiki/FAQ#q-i-get-access-denied-error-when-i-start-my-bot
