### ISSUE TITLE
_loadInventory is returning "Unknown response" error when response is valid but API results in body of {success: false, error: ''}

### ISSUE THREAD

**Issue by Mr-KoKa** [Alex7Kom/node-steam-tradeoffers#127]
So, _loadInventory method is checking:
```javascript
if (!body || !body.rgInventory || !body.rgDescriptions || !body.rgCurrency)
```
and if any of those are fullfilled it is returning
```javascript
return callback(new Error('Invalid Response'));
```
But there are (random) cases when Steam API results in {success: false, error: ''} and I would interpret it differently by inserting below code, before return line mentioned.
```javascript
if(body && !body.success){
	this.emit('debug', 'loading inventory: unknown steam api error');
	return callback(new Error('Unknown Steam API error'));
}
```
Or even before checking if body is false.

It's my first issue on github so, please excuse me if I didn't format text correctly.

**Edit**: I just had another idea, that you can actually check if there is any error in body response and print it out like:
```javascript
if(body && !body.success){
	if(body.error && body.error.length > 0){
		this.emit('debug', 'loading inventory: steam api error: ' + body.error);
		return callback(new Error('Steam API error: ' + body.error));
	} else {
		this.emit('debug', 'loading inventory: unknown steam api error');
		return callback(new Error('Unknown Steam API error'));
	}
}
```

**Comment by jhartzell** [comment]
You should read the first thread in this issues board and post this over on the official boards.

**Comment by Mr-KoKa** [comment]
I thought it's bug/feature request and posting it here fits.

**Comment by Mr-KoKa** [comment]
@Alex7Kom, you should also check if body.error isn't null as I did in example, because sometimes there is no error, and emiting that will probably throw.

**Comment by Alex7Kom** [comment]
If `body` itself is not `null` or `undefined` it won't throw.

**Comment by Mr-KoKa** [comment]
@Alex7Kom I had case where body wasn't null nor undefined and also body.success wasn't true, but there was no error, so without checking if body.error is anything it threw.

**Comment by Mr-KoKa** [comment]
@Alex7Kom Just found out when it can happen. When account has restriction due to steam guard when you try to load inventory (it requests https://steamcommunity.com/my/inventory/json/753/1/?trading=1 uri) the result is {success: false} so when you check that there is body, and it has !body.success, then when you will try to print out body.error, it will throw, because body is just {success: false} and nothing else.

**Comment by Alex7Kom** [comment]
Have you checked? In your case `body.error` will be just `undefined` and won't cause a reference error.
```js
var body = { success: false };
console.log(body.error)
// undefined
console.log('loading inventory: error: ' + body.error);
// loading inventory: error: undefined
```

**Comment by Mr-KoKa** [comment]
@Alex7Kom I haven't, so you're right, it should be just undefined without throwing, but I remember I had problems without checking if there is error, it looks like I was doing something else with it that caused it to throw.
