### ISSUE TITLE
BOT can't see offer in incoming offers

### ISSUE THREAD

**Issue by frook1** [Alex7Kom/node-steam-tradeoffers#130]
Hello,

Sometimes I have a problem with sending the offer from BOT to BOT 2.

How does this look:
BOT 1 sent offer to BOT 2 and BOT 2 can't see this offer in incoming offers.

This problem occurs in 5% of all offers. How can I fix this? Whether it is the fault of steam?

Regards,
safe

**Comment by Alex7Kom** [comment]
If the offer is sent without any errors then this issue is not related to `node-steam-tradeoffers` library.
