### ISSUE TITLE
error 403 while accepting offer

### ISSUE THREAD

**Issue by dSyncerek** [Alex7Kom/node-steam-tradeoffers#134]
hi,
i created a bot that has to accept all offers with no items from me.
while bot try to accept offer returns error 403. i read that can be problem with my api key, but i regenerated it many times, deleted it or setup() generated key.
I'm sure accepting is performing after successful login.
I don't know what is cause of my problem.
thanks for help.

**Comment by zohaibmir** [comment]
probably you have one week ban on your system.

**Comment by dSyncerek** [comment]
sometimes bot accept a few offers and after error comes again
