### ISSUE TITLE
Error: Cannot find module 'steam-logon'

### ISSUE THREAD

**Issue by Hohstapler** [Alex7Kom/node-steam-tradeoffers#138]
When I try to start offerbot.js I get this message.  
I've the newest version of node-steam.
Am I missing something?

**Comment by PokeRwOw** [comment]
You have included and instancied node-steam and node-steam-tradeoffers ? Send your code.

**Comment by Hohstapler** [comment]
My code is exactly the same as the original code of examples/offerbot.js 
I haven't changed anything.

http://pastebin.com/HxRVXjRu

**Comment by PokeRwOw** [comment]
Have you installed the module on your computer with a npm install ?

**Comment by Hohstapler** [comment]
Yes

**Comment by Alex7Kom** [comment]
You need to install 2 additional modules in order for examples to work: [steam-weblogon](https://github.com/Alex7Kom/node-steam-weblogon) and [steam-web-api-key](https://github.com/Alex7Kom/node-steam-web-api-key). I'll put this in README later.

**Comment by Hohstapler** [comment]
One more question, does it matter in which folders I install modules or they (theoretically) can be placed all in one folder?

**Comment by andrewda** [comment]
They should be installed in your `node_modules` folder, as it is the default folder to store the modules. It wouldn't be practical or make sense to put your modules in other folders.
