### ISSUE TITLE
Amount not working when sending trade offer

### ISSUE THREAD

**Issue by StevePavlin** [Alex7Kom/node-steam-tradeoffers#140]
Here is my send json:
```
{
"partnerSteamId":"76561198192437599", // My steam id
"accessToken":"9s9UlV2J", // My trade url token
// Bots items
"itemsFromMe":[{"appid":730,"contextid":2,"amount":1,"assetid":"2990713377"}, {"appid":730,"contextid":2,"amount":2,"assetid":"2990623398"}],
"itemsFromThem":[],
"message":"Here are your purchased items."
}
```

This results in:

Error: There was an error sending your trade offer.  Please try again later. (26)

The bot receives the items about 15 seconds prior to sending them like this, I tried a delay and it still does not work. Does anyone know why this is happening? I can send the same items if I use an amount of 1 but I need to be able to send the same item multiple times.

**Comment by StevePavlin** [comment]
Nevermind, figured this one out.

The assetid is ITEM SPECIFIC, therefore if you try to set an amount of 3 for one item it will not work. Change your loop accordingly and the offer will send properly.

**Comment by andrewda** [comment]
The amount property is there for items from, say, Spiral Knights, where you can have multiple of the same item with the same AssetID.

![image](https://cloud.githubusercontent.com/assets/10191084/9001618/92611408-370e-11e5-94fb-316159841473.png)
