### ISSUE TITLE
makeOffer assetid only works as string?

### ISSUE THREAD

**Issue by ArEsiiX** [Alex7Kom/node-steam-tradeoffers#141]
Hi,

I have a weird problem. When using the below code, everything works fine.

      itemsFromThem: [ // make sure you have the square brackets
        {
          "appid": 730,
          "contextid": 2,
          "amount": 1,
          "assetid": '2884007851'
        }
      ],

but when I replace "2884007851" with the variable "assetId" (which contains the right assesId, I checked) its not working? (error 26 -> wrong assetId)

      itemsFromThem: [ // make sure you have the square brackets
        {
          "appid": 730,
          "contextid": 2,
          "amount": 1,
          "assetid": assetId
        }
      ],

**Comment by scholtzm** [comment]
have you tried `assetId.toString()` ?

**Comment by ArEsiiX** [comment]
aaaand its solved. Thanks! Sorry, I should've checked that on before reporting an issue...
