### ISSUE TITLE
Incoming offers are not accepting

### ISSUE THREAD

**Issue by Sergeich182** [Alex7Kom/node-steam-tradeoffers#143]
I changed only these lines in the example (storehouse), because I need to accept all offers:
...
if (offer.trade_offer_state == 2){
              offers.acceptOffer({tradeOfferId: offer.tradeofferid});
			  console.log('Ok!');
          }
...
it worked perfectly, but now no longer. 
It is written in the console OK, but the offer is not accepted

**Comment by scholtzm** [comment]
Use the callback. Your code will always print 'Ok!', event if it fails.

https://github.com/Alex7Kom/node-steam-tradeoffers#acceptofferoptions-callback

**Comment by Sergeich182** [comment]
I'm noob at this , please write the code , if not difficult, thanks!

**Comment by LeCoffee** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/121

**Comment by Sergeich182** [comment]
i edit my code like this:
if (offer.trade_offer_state == 2){
            
              offers.acceptOffer({tradeOfferId: offer.tradeofferid}, callbackoffer);
			  console.log( callbackoffer );
            
          }
and received this:
![error](https://cloud.githubusercontent.com/assets/13593998/9019032/c4a56492-37ee-11e5-8cd5-39e31bf1e432.jpg)

sorry if i'm wrong, but i think steam is changin somthing in trade api ...

**Comment by andrewda** [comment]
`getOffers` returns an error for a reason. USE IT!

```js
offers.getOffers({
    get_received_offers: 1,
    active_only: 1,
    time_historical_cutoff: Math.round(Date.now() / 1000)
}, function(err, body) {
    if (err) throw err;
    // your code here...
```
