### ISSUE TITLE
Method getOfferToken throwing error.

### ISSUE THREAD

**Issue by Yorkii** [Alex7Kom/node-steam-tradeoffers#147]
You might consider surround url.parse with try-catch block or check if offerUrl is present. Sometimes it throws error because offerUrl is undefined for some reason :)

index.js - line 50

**Comment by Alex7Kom** [comment]
This change should solve the problem: https://github.com/Alex7Kom/node-steam-tradeoffers/commit/9b6e14bc44622f87fb816b838db1cb6c961f0f62.
