### ISSUE TITLE
My bot is throwing me an error when I want to send trade offers.

### ISSUE THREAD

**Issue by Dwynr** [Alex7Kom/node-steam-tradeoffers#150]
My bot is throwing this error:

![error](http://puu.sh/jRoPD/4441faf3dc.png)

And this is my code:

![error2](http://puu.sh/jRoRh/b858a85dbe.png)

It's getting trade offer queues out of the database with an itemstring (like AWP | Asiimov (Field-Tested)/AWP | Pit Viper (Field-Tested)/Chroma Case

I tried everything to get it work with no success.

Thanks in advance!

**Comment by scholtzm** [comment]
Wrong parameters, most likely in the items array you are sending.

**Comment by Dwynr** [comment]
Thanks for your answer.
Yes I know that error code 8 means missing parameters, but I dont know what is wrong there in my code..

**Comment by scholtzm** [comment]
I'm not sure what `sendItems` array is supposed to do but I'm pretty sure that's the culprit.

**Comment by Dwynr** [comment]
It's an itemstring which contains the items I want to send. Thats shouldn't be the issue..

**Comment by scholtzm** [comment]
You are most likely adding the same item ID twice.
