### ISSUE TITLE
What is contextId?

### ISSUE THREAD

**Issue by baimurzin** [Alex7Kom/node-steam-tradeoffers#154]
Can someone explain me what is contextId?
AppId is clear, but what is contextId I saw that is usually equals 2 but why?

**Comment by scholtzm** [comment]
Some inventories have multiple contexts (which are just sub-inventories). The one that comes to my mind is the Steam inventory which has multiple contexts. You can see these just by visiting your inventory @ steamcommunity.com.

However, most games, such as CSGO or TF2 have only one primary context.

**Comment by andrewda** [comment]
> However, most games, such as CSGO or TF2 have only one primary context.

And, by Steam logic, the primary context for these inventories should be `2`.

**Comment by baimurzin** [comment]
Thanks, guys
