### ISSUE TITLE
Bot not accepting offers 

### ISSUE THREAD

**Issue by HyperiaOfficial** [Alex7Kom/node-steam-tradeoffers#158]
Hello, my steambot is not accepting trade offers and just denies it
code:
```
offers.acceptOffer({tradeOfferId: offer.tradeofferid}, function(err, response) {
														console.log("Response: " + response + "\n" + "Error: " + err);
```
Output:
Response: undefined
Error: Error: There was an error accepting this trade offer.  Please try again l
ater. (11)

**Comment by MaiKaY** [comment]
To understand the error codes have a look [here](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd).
