### ISSUE TITLE
Can get partnerSteamId: from varable

### ISSUE THREAD

**Issue by kogan4ik** [Alex7Kom/node-steam-tradeoffers#160]
Hi, start using your module and find out strange thing.

socket.on('getPrize', function(id, userId){
            console.log('Try to give prize to user' + ' ' +  userId);
            Item.findById(id, function(err, item) {
                console.log(typeof userId);
                steamOffers.makeOffer ({
                    partnerSteamId: '76561198236425518',
                    itemsFromMe: [{
                        appid: item.appid,
                        contextid: item.contextid,
                        amount: 1,
                        assetid: item.itemId
                        }],
                    itemsFromThem: [],
                    message: 'This is test'
                    }, function(err, response) {
                        if (err) throw err;
                        logger.info(response);
                    }
                );
            });
        });

When i hardcode partnerSteamId all works but when i insert this from value i get an error 400 ? 
What does it mean? How to fix it?

**Comment by scholtzm** [comment]
Make sure your variable is a `string`. It works, I can assure you of that.

**Comment by andrewda** [comment]
Is userid a string?

**Comment by kogan4ik** [comment]
console.log(typeof userId);
This output string

**Comment by kogan4ik** [comment]
I try toString method too. I have no idea what to do

**Comment by kogan4ik** [comment]
Please can you tell me the deference between partnerAccountId and  partnerSteamId ? Maybe i can try second one

**Comment by scholtzm** [comment]
From the trade offer URL:

`https://steamcommunity.com/tradeoffer/new/?partner=X&token=Y`

`X` will be the account ID.

SteamID explained: https://developer.valvesoftware.com/wiki/SteamID#Format

**Comment by kogan4ik** [comment]
Steam id should look like a 'STEAM_0:0:138079895'? I need to insert this value to partnerSteamId ?

**Comment by andrewda** [comment]
No, `partnerSteamId` should be the SteamID 64 (I.e. steamcommunity.com/profiles/X, where X is the SteamID.
