### ISSUE TITLE
makeOffer using accessToken still returns error (8)

### ISSUE THREAD

**Issue by kiapwnz** [Alex7Kom/node-steam-tradeoffers#161]
Hello everybody,

I tried making a bot who can send trade offers to people who are not friends with the bot using this code:

```
console.log(row[i].userid);
var gamenum = row[i].id;
offers.makeOffer(
{
	partnerSteamId: row[i].userid,
	accessToken: row[i].token,
	itemsFromMe: item,
	itemsFromThem: []
}, function(err, response)
{
	if (err)
	{
		console.log(response);
		console.log(err);
	}
	console.log('Trade offer for queue ' + gamenum + ' sent!');
})
```

row[i].userid returns 76561198002011363 in console and .token returns '4rwb1sPT', both valid values according to the trade URL which is https://steamcommunity.com/tradeoffer/new/?partner=41745635&token=4rwb1sPT
Why do I still get Error 8 then?

This only happens with non-friended users.

Sincerely,
Kia.

**Comment by scholtzm** [comment]
#121 

Error 8 means the object you are passing to `makeOffer` is invalid.
Make sure `userid` is type of `string` and that the `item` variable is an `Object[]`.
