### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by dogmagames** [Alex7Kom/node-steam-tradeoffers#162]
After some time with bot logged on, im getting this error response when trying to create a new Offer.

**Comment by scholtzm** [comment]
Your cookies might be invalid.

**Comment by dogmagames** [comment]
My code is the same of example, what im doing wrong?

	steamClient.connect();
	steamClient.on('connected', function() {
	  steamUser.logOn(logOnOptions);
	});

	steamClient.on('logOnResponse', function(logonResp) {
	  if (logonResp.eresult === Steam.EResult.OK) {
		console.log('Logged in!');
		steamFriends.setPersonaState(Steam.EPersonaState.Busy);

		steamWebLogOn.webLogOn(function(sessionID, newCookie) {
		  getSteamAPIKey({
			sessionID: sessionID,
			webCookie: newCookie
		  }, function(err, APIKey) {
			offers.setup({
			  sessionID: sessionID,
			  webCookie: newCookie,
			  APIKey: APIKey
			}, function() {
			  logou = true;
			  ligaServer();
			});
		  });
		});
	  }
	});

**Comment by devhex** [comment]
Steam will disconnect or log you out every now and then. You should listen to steamClient's 'error' and 'loggedOff' events and login/reconnect respectively so that steam-tradeoffers get setup again.
```javascript
steamClient.on('loggedOff', function(){
	steamUser.logOn(logOnOptions);
});

steamClient.on('error', function(){
	steamClient.connect();
});
```

**Comment by scholtzm** [comment]
@devhex That has nothing to do with HTTP 401 errors though.

**Comment by dogmagames** [comment]
What is about then @scholtzm ?
Even if i run the example js file im getting 401 error about 1 hour later

**Comment by devhex** [comment]
@scholtzm You might be right, but are you sure that the cookies don't become invalid on logout?

**Comment by scholtzm** [comment]
@devhex It's all black box - hard to tell how it works internally. Now that I'm looking at the code, `node-steam` users most likely use `webapi_authenticate_user_nonce` to retrieve cookies, which *might* allow the cookies to be internally tied to your Steam network login session. I will do some brief testing later.

@dogmagames I'd try to call [webLogOn](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/storehouse.js#L47) again once you receive 401. See if new set of cookies helps.

**Comment by scholtzm** [comment]
@devhex You were right. Cookies become invalid after logging out. Here's my short testing script: https://gist.github.com/scholtzm/cbe2d243b60c8932a98e
