### ISSUE TITLE
Not accepting TradeOffers

### ISSUE THREAD

**Issue by QPandaQ** [Alex7Kom/node-steam-tradeoffers#165]
Hi. I'm sorry if its my fault but i have an problem with accepting incoming trades. 
I got this when i debuged what method 'acceptOffer' returns:
response.statusCode returns "500"
body.strError returns "There was an error accepting this trade offer. Please try again later. <24>"

**Comment by scholtzm** [comment]
You'll have to wait 7 days for the SteamGuard to allow you to trade on a new device.

**Comment by QPandaQ** [comment]
Omg.. stupid steam :/ Thanks for reply

**Comment by QPandaQ** [comment]
I have one more question. When i login to steam account via bot I recive in mail from steamguard another ip than when i'm logining via normal steam client. The 'new device' will work if there is another ip :v ?

**Comment by scholtzm** [comment]
IP doesn't matter. Make sure you are storing the SteamGuard file.

Also, #121.
