### ISSUE TITLE
Error: 504 on loadPartnerInventory

### ISSUE THREAD

**Issue by ENJATZ** [Alex7Kom/node-steam-tradeoffers#166]
Hi there!

I'm having a problem with a trade-bot. More in depth, I'm getting error 504 on loadPartnerInvetnory.

Any ideas?

**Comment by Alex7Kom** [comment]
5xx is indicating that the problem is on Steam side.

**Comment by scholtzm** [comment]
504 is Gateway Timeout. Just Steam being slow as usual.

**Comment by ENJATZ** [comment]
It's happening for a while. I mean I thought it should have been fixed by now.

**Comment by ENJATZ** [comment]
The problem with error 504 seems to have disappeared. Now I'm getting error 405 on getOffers.
