### ISSUE TITLE
An uncaughtException was found, the program will end.TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by Clickplaycorp** [Alex7Kom/node-steam-tradeoffers#170]
How to troubleshoot or fix this issue?

An uncaughtException was found, the program will end.TypeError: Cannot read property 'send' of undefined

**Comment by scholtzm** [comment]
https://github.com/steam-forward/node-steam-forum/issues/108

Looks like an issue with node-steam to me, not this package.
