### ISSUE TITLE
Steam bot starting but not accepting offers

### ISSUE THREAD

**Issue by OMGGDOG** [Alex7Kom/node-steam-tradeoffers#173]
So i was testing my bot but it doesn't accept the offers i'm giving it.
Can i have some help?

**Comment by andrewda** [comment]
You're not providing enough information; We'll need to see some code to be able to help.

**Comment by OMGGDOG** [comment]
Which type of the code the file?

**Comment by andrewda** [comment]
If I understand your question correctly, just paste the entire code [here](http://gist.github.com).

**Comment by OMGGDOG** [comment]
https://gist.github.com/OMGGDOG/1ca8b6d1b17f085dcc7c
Here.

**Comment by OMGGDOG** [comment]
I censored the passwords and important infomation.

**Comment by andrewda** [comment]
Well, this is the pure leaked code, so not much I can really do for ya. Here's just a general checklist, though:

- Is the bot's sentry file at least 7 days old?
- Can you accept offers manually?
- Can your bot *send* offers?

Lastly, and most importantly,

- Do you understand the code?

If you understand the code, you should have no problem fixing it.

**Comment by OMGGDOG** [comment]
The sentry file is not 7 days old.
And i can send the bot trade offers.
And when i login to the bot account i can accept the trades.
And i do understand a little bit of the code.

**Comment by andrewda** [comment]
> The sentry file is not 7 days old.

There's your problem.

**Comment by OMGGDOG** [comment]
Thank you! :)

**Comment by OMGGDOG** [comment]
Wait. I have a old bot and what happens if the sentry file is 7 days old?

**Comment by andrewda** [comment]
Once the sentry file is 7 days old, Steam "confirms" that you're the account you say you are.
