### ISSUE TITLE
Steam Mobile Authenticator functionality

### ISSUE THREAD

**Issue by askovi** [Alex7Kom/node-steam-tradeoffers#176]
Any chance we could get this implemented? Geel from scrap.tf made a library for C#. Anyway this could be ported to nodejs? Link: https://github.com/geel9/SteamAuth
After Dec 2nd all bots will be rendered useless without this. 

Thanks.

**Comment by Alex7Kom** [comment]
Nothing is impossible but this is irrelevant to the `node-steam-tradeoffers`.
