### ISSUE TITLE
There was an error sending your trade offer.  Please try again later. (26)

### ISSUE THREAD

**Issue by naksuasd** [Alex7Kom/node-steam-tradeoffers#177]
Hi, when i'm making trade offer, i got this error:
There was an error sending your trade offer.  Please try again later. (26)

With fast searching, i found similar threads but i got no help from them.
```javascript
offers.makeOffer({
                partnerSteamId: sId,
                accessToken: offerToken,
                itemsFromThem: itemsToGet,
                itemsFromMe: [],
                message: 'Deposit offer #'
            }
```

1. I have checked that SteamID (sId) is correct, accessToken is correct
2. sId is in my friend list
3. I'm not trade banned or anything wont limit me from trading
4. Items are tradeable

**Comment by srabouin** [comment]
26 usually means you're trying to get items you don't have, so you probably did not specify the correct id

**Comment by naksuasd** [comment]
I double checked that i'm requesting items witch user does have, and they are tradeable.

**Comment by scholtzm** [comment]
Hard code the values and see if that works.

**Comment by srabouin** [comment]
How are you defining the item ids? String?

**Comment by naksuasd** [comment]
itemsToGet contains array of items i got from loadPartnersInventory

**Comment by devhex** [comment]
Does the itemsToGet objects have the correct keys, like this?
```javascript
[{
    "appid": 440,
    "contextid": 2,
    "amount": 1,
    "assetid": "1627590398"
}]
```

**Comment by andrewda** [comment]
Well, it looks like you're making a jackpot site of some kind (`message: 'Deposit offer #'`) which is usually CS:GO. Are you attempting to send/receive CS:GO skins or TF2 items?

**Comment by naksuasd** [comment]
Oh, yeah it was about app id, sorry :+1:
