### ISSUE TITLE
Escrow hold duration?

### ISSUE THREAD

**Issue by halipso** [Alex7Kom/node-steam-tradeoffers#178]
Would be nice to see if user has escrow hold on his account.
You can find this info on trade page.

var g_daysMyEscrow = 0;
var g_daysTheirEscrow = 0;

**Comment by Alex7Kom** [comment]
Thanks, I'll look into it.

**Comment by tambu22** [comment]
whats with the Code needed to accept trades?

**Comment by halipso** [comment]
tambu22, we don't know yet if this is necessarily to use those codes.

**Comment by tambu22** [comment]
yes, steam api was updated :/

**Comment by halipso** [comment]
tambu22, link some proves then.

**Comment by tambu22** [comment]
https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService

post with changes : https://www.reddit.com/r/SteamBot/comments/3ux3ds/steam_dev_api_doc_has_been_updated/

**Comment by dolanmiu** [comment]
Will escrow be added to this library anytime soon?

**Comment by Alex7Kom** [comment]
Whatever is related to trades and is feasible to add will be added to the library sooner or later.

**Comment by lopataz** [comment]
If someone could pull a mobile confirmation, it would be nice! Maybe McKay can do this?

**Comment by scholtzm** [comment]
Everything needed is already available.
