### ISSUE TITLE
Mobile trade confirmations.

### ISSUE THREAD

**Issue by tambu22** [Alex7Kom/node-steam-tradeoffers#181]
"Starting 9 Dec, anyone losing items in a trade will need to have a Steam Guard Mobile Authenticator enabled on their account for at least 7 days and must not have turned off trade confirmations. Otherwise, to protect against unauthorized trades, items will be held by Steam for up to 3 days before delivery." 

-> Notification was updated, I guess it's all clear now.

**Comment by vejbuch** [comment]
https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/

**Comment by buddhapest** [comment]
@Alex7Kom  -  are you planning on doing any work around this?  if neither you nor @seishun are working on it, i'm going to go ahead and do a node version of the pertinent code from @geel9's https://github.com/geel9/SteamAuth/ as a separate module.

**Comment by scholtzm** [comment]
You'd be just [reinventing the wheel](https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/).

**Comment by Ax6** [comment]
@buddhapest isn't @DoctorMcKay steamcommunity module doing already that?
https://github.com/DoctorMcKay/node-steamcommunity
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity

**Comment by buddhapest** [comment]
good 'ole @DoctorMcKay !

**Comment by DoctorMcKay** [comment]
:)

**Comment by Alex7Kom** [comment]
`node-steam-tradeoffers` will allow supplying confirmations for trade offers. All other stuff including obtaining confirmations is outside the scope of the library.

**Comment by Alex7Kom** [comment]
Finally got to experiment with the new system and mobile confirmation system is indeed outside the scope of the library.

**Comment by webquali** [comment]
and from which library it depend?

**Comment by buddhapest** [comment]
easiest thing to do is to use https://github.com/DoctorMcKay/node-steamcommunity's `startConfirmationChecker`

```js
var Steamcommunity = require('steamcommunity');
var steamcommunity = new Steamcommunity();
...
// and after login
steamcommunity.setCookies(cookies);
steamcommunity.startConfirmationChecker(10000, identity_secret);
```
