### ISSUE TITLE
Error 50 :( What this?

### ISSUE THREAD

**Issue by vejbuch** [Alex7Kom/node-steam-tradeoffers#182]
Error: There was an error sending your trade offer.  Please try again later.<br>
<br>You cannot trade with kiełs0n [SaiyaJIN]. (50)

**Comment by scholtzm** [comment]
`AlreadyLoggedInElsewhere = 50;`

https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd
