### ISSUE TITLE
loadMyInventory and loadPartnerInventory not merged

### ISSUE THREAD

**Issue by lopataz** [Alex7Kom/node-steam-tradeoffers#184]
Hi,

I would like to know if it's possible to add the option to NOT merge "rgInventory" with "rgDescriptions" when loading the inventories and just return the json file as it is?

I need to have direct access to classid_instancid keys of rgDescriptions" without looping through each item of the inventory (that is very useful to optimize)

thank you

**Comment by andrewda** [comment]
Simply request http://steamcommunity.com/profiles/{steamid}/inventory/json/{appid}/{contextid}

For example, my CS:GO inventory would be http://steamcommunity.com/profiles/76561198092490523/inventory/json/730/2

**Comment by lopataz** [comment]
That's what I was doing before, but I would like to get inventory of private profile just from an offer they sent.

And when doing 7 times loops up to 500 within 20 seconds yes it does make difference, than direct access to the key

**Comment by lopataz** [comment]
I changed it myself in the code, it's not a big deal:
```
var options2={
    uri: uri,
    headers: {
      referer: communityURL + '/tradeoffer/' + offer +
        '/?partner=' + toAccountId(form.partner)
    },
    contextId: options.contextId
  };
  if ("notmerged" in options){ options2.notmerged=options.notmerged;}
  
  loadInventory.bind(this)(options2, callback);
......
......
......
Object.extend = function(destination, source) {
    for (var property in source) {
        if (source.hasOwnProperty(property)) {
            destination[property] = source[property];
        }
    }
    return destination;
};

function loadInventory(options, callback) {
	
	if("notmerged" in options){
		options.inventory = options.inventory || {rgInventory:{},rgDescriptions:{}};
	}else{
  options.inventory = options.inventory || [];
	}
.....
....
if("notmerged" in options){
		options.inventory.rgInventory = Object.extend(options.inventory.rgInventory,body.rgInventory) ;
		options.inventory.rgDescriptions = Object.extend(options.inventory.rgDescriptions,body.rgDescriptions) ;
	}else{
  options.inventory = mergeInventory(options.inventory, body, options.contextId);
	}
```

**Comment by scholtzm** [comment]
> it's not a big deal

Until you need to update the package?

**Comment by Alex7Kom** [comment]
What is your use case for this?

**Comment by Alex7Kom** [comment]
Hope this is what you were looking for: https://github.com/Alex7Kom/node-steam-tradeoffers/commit/e0b85955f9ea5fbcac6bcb10fcb0ad4f24049c41.

**Comment by lopataz** [comment]
Yes that must be it! Good job! thank you very much for that, 

This is useful to me when I want a direct access to a description from the classid key.
