### ISSUE TITLE
Error: 403 - When getOffers

### ISSUE THREAD

**Issue by Marow** [Alex7Kom/node-steam-tradeoffers#185]
I wanted to setup my node Bot for escrow

He can Logged in, getting Mobile Auth Code, all works correctly.
But when he will make "getOffers", he get an Error 403.
I cant find what the problem is!

```
offers.getOffers({
		get_received_offers: 1,
		active_only: 1,
  		time_historical_cutoff: Math.round(Date.now() / 1000)
	}, function(error, body) {
		console.log('testprice2');
		if(error) console.log(error); return;
		if(body.response.trade_offers_received){
```
After the "testprice2" Log, the Error comes and looks like

```
[Error: 403]
```
Nothing more and i cant find an Error.

I already regenarted the API Key.

**Comment by buddhapest** [comment]
403 is access denied

you logged in used `node-steam` or `node-steam-user`?  did you pass the cookies and sessionID to setup?

see https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js#L79-L99

**Comment by Freaders** [comment]
im geting same error, did you update your steam-tradeoffers plugin from version earlier than 1.2.4?

**Comment by ylms** [comment]
Yeah that's all about version. You need to modify your codes.

**Comment by Dozorov** [comment]
I have same problem! doing API call GetTradeOffers/v1: 403

Use:

offers.setup({
			sessionID: webSessionID,
			webCookie: newCookie
		}, function(){
			if (typeof callback == "function") {
				callback();
			}
		});

With: 
getSteamAPIKey({
                    sessionID: webSessionID,
                    webCookie: newCookie
                }, function(err, APIKey) {
						offers.setup({
							sessionID: webSessionID,
							webCookie: newCookie,
							APIKey: APIKey
						}, function(){
							if (typeof callback == "function") {
								callback();
							}
						});
            });
Dont have problem!

**Comment by vejbuch** [comment]
@Dozorov I do not understand, can you help?

**Comment by vejbuch** [comment]
```
root@vm16012:~# node /root/node_modules/steam-tradeoffers/examples/sell3.js
GHTBN
socket timed out
socket closed
connecting to 72.165.61.185:27017
connected
encrypt request
handshake complete
Logged in!
/root/node_modules/steam-web-api-key/index.js:10
  options.webCookie.forEach(function (name) {
                   ^
TypeError: Cannot read property 'forEach' of undefined
    at getAPIKey (/root/node_modules/steam-web-api-key/index.js:10:20)
    at /root/node_modules/steam-tradeoffers/examples/sell3.js:109:10
    at IncomingMessage.<anonymous> (/root/node_modules/steam/lib/handlers/user.j
s:104:9)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by Dozorov** [comment]
@vejbuch Add me on skype: dozor-cool

**Comment by Gergo4961** [comment]
Change:

offers.setup({
sessionID: webSessionID,
webCookie: newCookie

To:

offers.setup({
sessionID: webSessionID,
webCookie: newCookie,
APIKey: apik(the bot's api key)

And try again!
