### ISSUE TITLE
getHoldDuration  "Error: Can't g et hold duration"

### ISSUE THREAD

**Issue by tambu22** [Alex7Kom/node-steam-tradeoffers#188]
my code its:

    offers.getHoldDuration({partnerAccountId: offer.accountid_other}, function(response)
    {
             console.log(response);
    });

i try with the token:

    offers.getHoldDuration({partnerSteamId: offer.steamid_other, accessToken: token}, function(response)
    {
             console.log(response);
    });

and get NULL response.

**Comment by spyrek10** [comment]
Same problem here.

**Comment by Alex7Kom** [comment]
Don't forget to provide `accessToken`, otherwise it will work only with friends.

**Comment by spyrek10** [comment]
Can I get accessToken without querying database for tradelink to get token?

**Comment by tambu22** [comment]
my bot dont have database of users, how can i get token? and in the wiki said "Optional"

**Comment by andrewda** [comment]
You cannot get the accessToken without the user providing it. The purpose of the access token is so that random people can't send you trade offers if you don't want them to, so it generates a random accessToken that you provide to sites and people who you want to trade with.

**Comment by tambu22** [comment]
okay but now i try with the token and get null response!

**Comment by spyrek10** [comment]
Same here, null response.

**Comment by tambu22** [comment]
FIXED, TNKS!!! 


     offers.getHoldDuration({partnerSteamId: offer.steamid_other, accessToken: token}, function(err,     response)
	                        {
	                       if (err)
	                        {
	                            offers.declineOffer({tradeOfferId: offer.tradeofferid});
	                            return;
	                        }
	                        console.log(response);
});
