### ISSUE TITLE
getHoldDuration needs partner token

### ISSUE THREAD

**Issue by jmate0321** [Alex7Kom/node-steam-tradeoffers#190]
Hello there!

getHoldDuration is useless if we don't know the token of the user we are trading with.
It could be done without a token, by changing the URL to "https://steamcommunity.com/tradeoffer/" + tradeofferid + "/"

Where tradeofferid is a currently active offer ID between us and the other guy.

Source:
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/commit/61408cc9246c7b82e9bb4987dec31a6f167a3779

Could you implement this? Thank you.

**Comment by Dozorov** [comment]
+

**Comment by Alex7Kom** [comment]
It is useful, if you want to know hold duration beforehand. Hold duration of an existing trade is another story.
