### ISSUE TITLE
Can't use getHoldDurations()

### ISSUE THREAD

**Issue by danifantom** [Alex7Kom/node-steam-tradeoffers#192]
Hello, I'm using node-steam-tradeoffers on version 1.2.3. I tried updating to the lates version but I only get Error: 403 on offers.getOffers(). Im currently using these versions.

    npm install steam@0.6.8
    npm install steam-tradeoffers@1.2.3
    npm install steam-userinfo@1.1.5

If I update any of them my bot stops working, and new errors come out.
Is there an alternative for this method?
I heard about getEscrowDuration() but couldnt find about it in any repo documentation.
PS: I can manage to get the partner's token so I can have it if I need it!
Thank You very much!

**Comment by jwigley** [comment]
When you update to the latest versions, you will also need to update your code to match. There has been breaking changes that mean your old code will need to be changed.

Take a look at the [examples](https://github.com/Alex7Kom/node-steam-tradeoffers/tree/master/examples]).

`getHoldDuration` is documented in the [README](https://github.com/Alex7Kom/node-steam-tradeoffers/tree/cbd6c98acaf59079868187a926ebe60e9d98af7c#getholddurationoptions-callback).

**Comment by Alex7Kom** [comment]
What @jwigley said.
