### ISSUE TITLE
Why bot disconnect，it can not connect in an hour?

### ISSUE THREAD

**Issue by meitinglei** [Alex7Kom/node-steam-tradeoffers#193]
I have launched my bot ,logOnResponse is ok and ''Logged in!';
When some error from steam ,it disconnect，bot will reconnect and success  before；
but now  it failed to reconnect;
when I launch the bot  in the next few minutes again，it always failed;
but when I launch the bot in annother PC,logOnResponse is ok and ''Logged in!';
Do you have the same problem？

**Comment by meitinglei** [comment]
I can launch the bot again on the same device after an hour

**Comment by Nikoly0072** [comment]
Вы используете файлы ssfn + код от мобильного индификатора ?

**Comment by Alex7Kom** [comment]
This is not a `node-steam-tradeoffers` issue.

@Nikoly0072 Please use English here.
