### ISSUE TITLE
GetHold duration broken ?

### ISSUE THREAD

**Issue by Alex-Nabu** [Alex7Kom/node-steam-tradeoffers#194]
Error: Can't get hold duration
    at SteamTradeOffers.<anonymous> (C:\Users\Alex\Desktop\bot 2.0\node_modules\steam-tradeoffers\index.js:498:23)

Thats the exact error i'm getting. is it possible that the info to retrieve this on steam's side may have changed. or is this an isolated incident ?

**Comment by Alex7Kom** [comment]
It certainly works and is not broken.
