### ISSUE TITLE
Can't get hold duration

### ISSUE THREAD

**Issue by halipso** [Alex7Kom/node-steam-tradeoffers#197]
After certain time library always returns this error "retrieving hold duration: can't get hold duration"

**Comment by kingjerod** [comment]
I get this error message immediately with the getTradeHoldDuration function, right after I start a successful trade. Things work (so far) with just using the getHoldDuration function.

**Comment by ipaspeak** [comment]
What is the http response code? If it's 401 it means that your cookies/ session has expired.

**Comment by kingjerod** [comment]
I get a 200 status code. This is seconds after I've started the trade, and seconds after I just logged in, I would be surprised if the cookies expired in under a minute (but hey anything is possible with Steam).

**Comment by fedorovvldmr** [comment]
When using getTradeHoldDuration I always get an error "Can't get hold duration"

**Comment by DDragones** [comment]
```javascript
offers.getTradeHoldDuration({tradeOfferId: offer.tradeofferid}, function (err, hold) {
if (err) {
	weblogon();
	setTimeout(function () {
		offers.getTradeHoldDuration({tradeOfferId: offer.tradeofferid}, function (err, hold) {
			if (err) {
				offers.declineOffer({tradeOfferId: offer.tradeofferid});
				weblogon();
			} else {
				if (hold.their != 0) {
					offers.declineOffer({tradeOfferId: offer.tradeofferid});
				}
			}
		});	
	}, 5000);
} else {
	if (hold.their != 0) {
		offers.declineOffer({tradeOfferId: offer.tradeofferid});
	}
}
});
```

It works :)

**Comment by fedorovvldmr** [comment]
DDragones, for me It works only in some cases.

**Comment by DDragones** [comment]
fedorovvldmr, you can just create loop function with ```weblogon();```, while error.
I think you are from Russia? If true, I can help you in skype.

**Comment by fedorovvldmr** [comment]
> I think you are from Russia? If true, I can help you in skype
Да) fedorov.vldmr

**Comment by DDragones** [comment]
```javascript
function getTradeHold (tradeofferid) {
	offers.getTradeHoldDuration({tradeOfferId: tradeofferid}, function (err, hold) {
	if (err) {
	    weblogon();
	    setTimeout(getTradeHold(tradeofferid), 5000);
	} else {
	    if (hold.their != 0) {
	        offers.declineOffer({tradeOfferId: offer.tradeofferid});
	    }
	}
	});
}
```

I create it function now for you, it must work, but i don't test it.
Just recursion function while error getting hold.

**Comment by D3uxx** [comment]
I have tested using both above and still get the same response.

Under it I get "undefined" using:

 console.log(hold);

My code is: 

function getTradeHold (tradeofferid) {
    offers.getTradeHoldDuration({tradeOfferId: tradeofferid}, function (err, hold) {
    if (err) {
        weblogon();
        setTimeout(getTradeHold(tradeofferid), 5000);
		console.log(hold);
    } else {
        if (hold.their !== 0) {
            offers.declineOffer({tradeOfferId: offer.tradeofferid});
			console.log('HAS TRADE HOLD.');	
        }
    }
    });
}

**Comment by fedorovvldmr** [comment]
Regenerate ApiKey. Problem solved for me.

**Comment by Alex7Kom** [comment]
After the fix https://github.com/Alex7Kom/node-steam-tradeoffers/pull/196 error messages should be more specific.

**Comment by fedorovvldmr** [comment]
Error: 403 (((

**Comment by buddhapest** [comment]
> Error: 403 after login in getOffers (((
are you sure you're passing in the cookies you got from login?

**Comment by fedorovvldmr** [comment]
```javascript

var gSessionID = false;

SteamClient.on('webSessionID', function(webSessionID) {
	helper.msg('Event "webSessionID" sessionID: '+webSessionID);
	helper.msg('Event "webSessionID" SteamClient.sessionID: '+SteamClient.sessionID);

	gSessionID = webSessionID;

	reWebLogOn();
});

SteamClient.on('logOnResponse', function(logonResp) {
	helper.msg('Event "logOnResponse": '+JSON.stringify(logonResp));

	if(logonResp.eresult === Steam.EResult.OK)
	{
		helper.msg('Logged in!');
		SteamFriends.setPersonaState(Steam.EPersonaState.Online);

		reWebLogOn();
	}
});

function reWebLogOn(callback) {

	steamWebLogOn.webLogOn(function(sessionID, newCookie) {

		//if(gSessionID)
		//{
		//	sessionID = gSessionID;
		//}
		//sessionID = SteamClient.sessionID;

		helper.msg('webLogOn: '+JSON.stringify({
				sessionID: sessionID,
				cookie:    newCookie
			}));

		getSteamAPIKey({
			sessionID: sessionID,
			webCookie: newCookie
		}, function(err, apiKey) {
			if(err)
			{
				helper.msg('Ошибка в событии logOnResponse ERROR '+err);
			}
			else
			{
				helper.msg('getSteamAPIKey: '+apiKey);

				offers.setup({
					sessionID: sessionID,
					webCookie: newCookie, //APIKey:    config.apiKey
					APIKey:    apiKey
				});

				if(typeof callback == "function")
				{
					callback();
				}
			}
		});
	});
}

```
