### ISSUE TITLE
#onGetOffers won't return body.response?

### ISSUE THREAD

**Issue by naksuasd** [Alex7Kom/node-steam-tradeoffers#205]
Hi, just a quick question what may cause my problem. I had my script working well for a while, but suddenly it started causing this problem.

First of all, my code:

```javascript

    if (number > 0) {
        helper.msg('New offers: ' + number);

        function getOffers() {
            offers.getOffers({
                get_received_offers: 1,
                active_only: 1
            }, onGetOffers);
        }

        function onGetOffers(error, body) {
            if (error) {
                if (retryCnt >= 0) {
                    getOffers();
                    retryCnt--;
                }

                helper.log('Error getting offers', 692, error);
            }

            // Check offers
            if (body) {

                helper.msg("Step 1");

                if (body
                    && body.response
                    && body.response.trade_offers_received) {

                    helper.msg("Step 2");


```

So, it print's "Step1" for me, but not "Step 2". Any idea's what may cause this problem. It have been working earlier, and if i remember correctly, i have not changed this code.

Thanks in advance! :)

**Comment by Gergo4961** [comment]
I'm having the same problem too, the body is ,,unknown" and there is no error shown.

**Comment by Gergo4961** [comment]
Use the bot's API, solved it for me.

**Comment by naksuasd** [comment]
What do you mean exactly?

**Comment by Gergo4961** [comment]
You need an API key to make the bot work, but if you use the API key of your own account and not the one that is generated for the bot you might run into this issue.

Log in to the bot's account and go here: https://steamcommunity.com/dev/apikey

Get the new API and try it with this!

**Comment by naksuasd** [comment]
I will try with one witch bot generates. Thanks for quick answer, i will leave this issue open till i have confirmed this issue.

**Comment by naksuasd** [comment]
Yea, that was the thing witch caused that issue. Closed
