### ISSUE TITLE
Can't send trade offer, what Am I doing wrong?

### ISSUE THREAD

**Issue by danifantom** [Alex7Kom/node-steam-tradeoffers#207]
I must send 1 item stored on my database SO I'm making like this:
    mysqlConnection.query('SELECT * FROM `queue` WHERE `status`=\'waiting\' LIMIT 1', function(err, row, fields) {
        if (err) throw err;
        var token= row[0].token;
        var queueId= row[0].id;
        var itemAssetId= row[0].assetid;
        var partnerId= row[0].userid;
    var toSend= {
                appid: 730,
                contextid: 2,
                amount: 1,
                assetid: itemAssetId
            }
    offers.makeOffer({
        	    partnerSteamId: partnerId,
        	    itemsFromMe: toSend,
        	    accessToken: token,
        	    itemsFromThem: [],
        	    message: 'You won on CSGOWise.com\'s auction! Here if your item!'
        	}, function(err, response) {
    });
    });

That's not all my code but You can see what I'm doing.
Im getting this error on node.js console:
`TypeError: str.indexOf is not a function`

What Am I doing wrong?

**Comment by andrewda** [comment]
#121 - Also, this is not a library error in the slightest. Your `str` is not a string nor an array (my guess is that it's `undefined`), so the `indexOf` method cannot be used on it.
