### ISSUE TITLE
Error: 403

### ISSUE THREAD

**Issue by Nydylier** [Alex7Kom/node-steam-tradeoffers#209]
Hello,
Untill 23.12 bots were working fine. On 23.12 "Error.403" appears nearly all the time when bots are using getOffer, loadMyInventory i makeOffer. What does it mean?

Merry Christmas! ;)

**Comment by Alex-Nabu** [comment]
@Nydylier  MC. means web session expired. Just relogin and continue

**Comment by DDragones** [comment]
@Nydylier you must install APIKey of bot to object ```offers``` :)
Code of ```weblogon()``` :
``` javascript
function weblogon() {
	steam.webLogOn(function(newCookie) {
		offers.setup({
			sessionID: globalSessionID,
			webCookie: newCookie,
			APIKey: 'APIKey' // paste here
		}, function(err) {
			if (err) {
			}
		});
	});	
}
```

Merry Christmas ;D

**Comment by Nydylier** [comment]
1. I doing manual restart bot and "Error: 403".
2. I give APIkey in setup()... "Untill 23.12 bots were working fine."

**Comment by DDragones** [comment]
@Nydylier give your code.

**Comment by naksuasd** [comment]
Having exactly same problem. Any solutions?

**Comment by Nydylier** [comment]
My problems were caused by steam lags.
