### ISSUE TITLE
Issue with adding Get hold duration

### ISSUE THREAD

**Issue by imiszel** [Alex7Kom/node-steam-tradeoffers#211]
Im trying to add getholdduration but it is too slow and getting hold duration after accept offer, so it cant decline. 
How it should look? My code : http://pastebin.com/j1VupZfi (its raw code here)

**Comment by jwigley** [comment]
`getHoldDuration` has a callback. You can use that so you only accept/decline once it's returned the hold duration.

**Comment by imiszel** [comment]
http://pastebin.com/2yu6qVeQ sth like it? But idk where to paste it to execute rest of code if its positive .

**Comment by imiszel** [comment]
i should paste it somethere http://pastebin.com/4ffW4vUJ but idk exactly where

**Comment by jwigley** [comment]
Going off your first lot of code, would this make sense?

```JavaScript
setTimeout(function () {
    offers.getTradeHoldDuration({tradeOfferId: offer.tradeofferid}, function (err, hold) {
        if (err) {
            offers.declineOffer({tradeOfferId: offer.tradeofferid});            
        } else {
            if (hold.their != 0) {
                offers.declineOffer({tradeOfferId: offer.tradeofferid});
            }
            else {
                // accept the offer
                // ...
            }
        }
    });
...
```

**Comment by imiszel** [comment]
[14:38:37:102] Message: "New offers: 1"
[14:38:37:623] Message: "Current game offers" at row:716, Content:  [ '930393940' ]
[14:38:37:630] Message: "Sending api request..."
[14:38:37:895] Message: "Received api request!"
retrieving hold duration: can't get hold duration

**Comment by imiszel** [comment]
now i cant get hold duration
