### ISSUE TITLE
Can i use  getItems without login ?

### ISSUE THREAD

**Issue by pavell-hyuna** [Alex7Kom/node-steam-tradeoffers#212]
I have login funciton with php . Then i do getItems with node-steam-tradeoffers and i always get error "SteamGuardMobile" . As i understood this error became because i have logined several times . I tried to use previous twoFactorCode but i got the same. Can i get it work ?

**Comment by pavell-hyuna** [comment]
I found a solution . But now i'm getting empty array from it . Maybe someone have suggestions for it ?

**Comment by g00se** [comment]
getItems works only with trade where u receiving items
if you give items, you must use 
offers.getOffer({tradeOfferId: tradeofferid},function(err,trade) {
console.log("%j",trade.response.offer.items_to_give);
});

**Comment by pavell-hyuna** [comment]
yes it's recieve trade . First i accept trade and then i try to get items from trade
