### ISSUE TITLE
loadMyInventory error 429

### ISSUE THREAD

**Issue by gurudexx** [Alex7Kom/node-steam-tradeoffers#218]
I have problem with loadMyInventory. I often get error #429.

trade0.loadMyInventory({ appId: appID.CSGO, contextId: contextID.CSGO }, function (err, allItems) {
            if (err==null && allItems != null && allItems.length > 0) {
                          //CODE
            }
}

This is my code. I get err=429 and allItems=null

Thx

**Comment by Netifriik** [comment]
[429 - Too Many Requests](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
