### ISSUE TITLE
getOffers - Error: 403

### ISSUE THREAD

**Issue by Dezash** [Alex7Kom/node-steam-tradeoffers#219]
```javascript
function checkoffers(number) {
	if (number > 0) {
		offers.getOffers({
			get_received_offers: 1,
			active_only: 1,
			get_sent_offers: 0,
			get_descriptions: 1,
			language: "en_us",
		}, function(error, body) {
			if(error){ console.log(error); return;}
  });
 }
}
```

Output is: [Error: 403].
Am I passing wrong options or is there something wrong with Steam?
Adding "serverid: 1" doesn't help.

**Comment by Dezash** [comment]
I have added APIKey to offers.setup and now I don't get an error but I get an empty array for body.response in getOffers function.

				offers.setup({
					sessionID: sesID,
					webCookie: newCookie,
					APIKey: api_key
				}, function(err) {
					if (err) {
						console.log("Offers setup: "+err);
					}
				});

**Comment by esvills** [comment]
Every day ERROR 403, but api key correct.

**Comment by buddhapest** [comment]
> Every day ERROR 403, but api key correct. 

have you tried it directly from steam or a browser?

**Comment by naksuasd** [comment]
Having same problem, any solutions?

**Comment by mihayy5** [comment]
How did you exactly added API key to  _offers.setup_ ?

**Comment by mihayy5** [comment]
Also does necessary need to be the BOT API because I can't get a API for my BOT (Limited Account)

**Comment by dsisco11** [comment]
If you mean you aren't using the API key assigned to that bot's steam account then yes, the key you pass to web api functions which return non-public account information (things that only your bot can see about itself) you have to use the API key assigned to that steam account.

**Comment by tuktun** [comment]
Maybe your bot account is limited? Did you donated 5$ to your account?

**Comment by mihayy5** [comment]
Nah, I fixed it, thank's anyway.
