### ISSUE TITLE
 Cannot read property 'get' of undefined 

### ISSUE THREAD

**Issue by esvills** [Alex7Kom/node-steam-tradeoffers#220]
/node_modules/steam-tradeoffers/index.js:477
  this._requestAPI[httpMethod](params, function(error, response, body) {
                  ^
TypeError: Cannot read property 'get' of undefined

Today there was a error. Previously, there was.
In Russian я не совсем особо говорю на англ, но сегодня появилась такая ошибка.

**Comment by Alex7Kom** [comment]
You are calling some of the methods before `.setup()`.
