### ISSUE TITLE
Problem retrieving the Trade Hold from getTradeHoldDuration

### ISSUE THREAD

**Issue by Exokay88** [Alex7Kom/node-steam-tradeoffers#222]
Good morning everyone.  
My Problem today is, that im not able to get the getTradeHoldDuration. 

Heres the code of the gethold function
http://pastebin.com/JUaF0uCx 
If you wonder about the amount of Mysql statements is because im using my database as a kinda state machine.  and i yet didnt make a function to change it to available
Is my callback wrong or is setTimeout() not working?
Everything else is working just the getTradeHold doesn't work at me.
Im setting up my API Key on login and generate new Cookies every 20 Min via Interval.  
It showed the TradeHold once but it took like 10 seconds to reply it from Steam.  
Thanks for helping me guys.

**Comment by Cronick** [comment]
Think I have sort of the same problem at the moment, but not quite sure.

**Comment by Exokay88** [comment]
offers.getTradeHoldDuration({tradeOfferId: offer.tradeofferid}, function (err, hold) {
							if (err) {
							    offers.declineOffer({tradeOfferId: offer.tradeofferid});            
							    return;       
							} else {
							     if (hold.their != 0) {
							        console.log(their.hold);
							        offers.declineOffer({tradeOfferId: offer.tradeofferid});            
							        return;
							    }
							}
							console.log(their.hold); //make it visual too see something atleast.
						});

**Comment by Alex7Kom** [comment]
Is this issue still relevant?

**Comment by Exokay88** [comment]
i would not say so because i stopped working on it.
