### ISSUE TITLE
HELP Can't get hold duration

### ISSUE THREAD

**Issue by Sweeeeep** [Alex7Kom/node-steam-tradeoffers#223]
always returning undefined :(

code:

    offers.getTradeHoldDuration({tradeOfferId: offer.tradeofferid}, function (err, hold) {
    console.log(offer.steamid_other);
        console.log(offer.accessToken);
    if (err) {
        requestify.post('http://'+config.domain+'/api/haventescrow', {secretKey: config.secretKey , steamid: offer.steamid_other});
        //console.tag('ESCROW').log(hold.their+' disabled');
        offers.declineOffer({tradeOfferId: offer.tradeofferid});            
        return;       
    } else {
         if (hold.their != 0) {
            console.log(hold);
            requestify.post('http://'+config.domain+'/api/haventescrow', {secretKey: config.secretKey , steamid: offer.steamid_other});
            console.tag('ESCROW').log(hold.their+' disabled');
            offers.declineOffer({tradeOfferId: offer.tradeofferid});            
            return;
        }
    }
    });

**Comment by Exokay88** [comment]
did u try console.log(offers.accessToken); ?

**Comment by kudo070** [comment]
Мой код :dango:

**Comment by Nikoly0072** [comment]
Такую шляпу ток ты можешь придумать -_-

**Comment by Alex7Kom** [comment]
#121
