### ISSUE TITLE
TypeError: Not a buffer

### ISSUE THREAD

**Issue by BlackOnix** [Alex7Kom/node-steam-tradeoffers#225]
Hello.When I try to send a weapon I get the error
http://prntscr.com/9so7tw
Help Me

**Comment by Alex7Kom** [comment]
This error has nothing to do with `steam-tradeoffers` module.

**Comment by BlackOnix** [comment]
And what is that? It occurs when you send the item

**Comment by Alex7Kom** [comment]
Ask the person who wrote your bot.
