### ISSUE TITLE
Problem with Long.js

### ISSUE THREAD

**Issue by Celestriall** [Alex7Kom/node-steam-tradeoffers#229]
/var/www/bot/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:203
        if (str.length === 0)
               ^
TypeError: Cannot read property 'length' of undefined
    at Function.fromString (/var/www/bot/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:203:16)
    at toAccountId (/var/www/bot/node_modules/steam-tradeoffers/index.js:362:15)
    at SteamTradeOffers.getHoldDuration (/var/www/bot/node_modules/steam-tradeoffers/index.js:64:42)
    at /var/www/bot/bot.js:762:42
    at SteamTradeOffers.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/index.js:429:7)
    at Request.self.callback (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:962:12)

**Comment by Alex7Kom** [comment]
Please post a minimal test case.

**Comment by Celestriall** [comment]
Long.fromString = function fromString(str, unsigned, radix) {
        if (str.length === 0)
            throw Error('number format error: empty string');
        if (str === "NaN" || str === "Infinity" || str === "+Infinity" || str === "-Infinity")
            return Long.ZERO;
        if (typeof unsigned === 'number') // For goog.math.long compatibility
            radix = unsigned,
            unsigned = false;
        radix = radix || 10;
        if (radix < 2 || 36 < radix)
            throw Error('radix out of range: ' + radix);

        var p;
        if ((p = str.indexOf('-')) > 0)
            throw Error('number format error: interior "-" character: ' + str);
        else if (p === 0)
            return Long.fromString(str.substring(1), unsigned, radix).negate();

**Comment by Alex7Kom** [comment]
You are supposed to post your own code, not the code of the library. What you are trying to do at /var/www/bot/bot.js:762:42?

**Comment by Celestriall** [comment]
steamOffers[currentAccountBotName].getHoldDuration({
							partnerAccountId: accountid,
							accessToken: token
						}, function (err1, duration) {
							if (!err1) {
								
								if ((duration.my == 0) && (duration.their == 0)) {

									var partnerInventoryRetry = 5;

									var loadPartnerInventory = function() {

										partnerInventoryRetry--;

										steamOffers[currentAccountBotName].loadPartnerInventory({
											appId: 730,
											contextId: 2,
											partnerAccountId: accountid
										}, function(err, items) {
											
											if (err) {
												console.log('Error loadPartnerInventory ' + err);
												if (partnerInventoryRetry >= 0) {
										
													console.log('Retry loadPartnerInventory step: ' + partnerInventoryRetry);
													setTimeout(function() {
														loadPartnerInventory();
													}, 2000);
										
												} else {
													userIDPendingOffer.splice(userIDPendingOffer.indexOf(user.userid), 1);
												}										
											} else {
											
												var lengthToCheck = data.items.length,
													itemsExist = 0,
													itemsInfo = [];

												for (var i = 0; i < items.length; i++) {
													for (var z in data.items) {
														if (items[i].id === data.items[z] && items[i].tradable) {
															itemsInfo.push({
																name: items[i].market_hash_name
															});
															itemsExist += 1;
															continue;
														}
													
														if (itemsExist === lengthToCheck) break;
													}
												}
