### ISSUE TITLE
[Error: There was an error sending your trade offer. Please try again later. (8)]

### ISSUE THREAD

**Issue by madlybong** [Alex7Kom/node-steam-tradeoffers#235]
[Error: There was an error sending your trade offer.  Please try again later. (8)]

Every time i'm trying to trade ....

MY TRADE REQUEST EXACTLY IS

```
{ partnerSteamId: '765611980********',
  itemsFromMe:
   [ { appId: 570,
       contexId: 2,
       amount: 1,
       assetId: '36107323_23013902' },
     { appId: 570,
       contexId: 2,
       amount: 1,
       assetId: '61240980_23013902' } ],
  itemsFromThem: [] }
```
or

```
{ partnerSteamId: '765611980********',
  itemsFromMe:
   [ { appid: 570,
       contexid: 2,
       amount: 1,
       assetid: '36107323_23013902' },
     { appid: 570,
       contexid: 2,
       amount: 1,
       assetid: '61240980_23013902' } ],
  itemsFromThem: [] }
```

**any help please ???**

**Comment by jwigley** [comment]
`contexid` -> `contextid`

**Comment by madlybong** [comment]
i'm really very sorry ... but now it's [Error: 401]

BTW i'm just starting up with this steam thing ... Thank you very much for replying ...

**Comment by jwigley** [comment]
No worries. However this issues tracker is for issues with `node-steam-tradeoffers` only.

See https://github.com/Alex7Kom/node-steam-tradeoffers/issues/121.

Good luck!

**Comment by madlybong** [comment]
Okay i got it ... My apologies ... Thanks again ...

**Comment by madlybong** [comment]
Ok I've half working code right now ... If i trade to **bot account** _(node steam still running)_ from my account, bot auto accepts the offer and everything is fine ...

but when i do the same thing from makeOffer it gives me this error 

**[Error: There was an error sending your trade offer.  Please try again later. (26)]**

**ex. 1**
```
{ partnerSteamId: '765611980********',
  itemsFromMe:
   [ { appid: 570,
       contextid: 2,
       amount: 1,
       assetid: '136107323_230139020' },
     { appid: 570,
       contextid: 2,
       amount: 1,
       assetid: '161240980_230139020' } ] }
```

**ex. 2**
```
{ partnerSteamId: '765611982********',
  accessToken: '****',
  itemsFromMe: [ { appid: 570, contextid: 2, amount: 1, assetid: '370181842_0' } ],
  itemsFromThem: [] }
```

**Comment by Alex7Kom** [comment]
You were already pointed to #121.
This is not an issue with `node-steam-tradeoffers`. Please double check your own code.
