### ISSUE TITLE
Analyse tradeoffer content?

### ISSUE THREAD

**Issue by iJamesPHP** [Alex7Kom/node-steam-tradeoffers#240]
How can I analyse the content of a tradeoffer being sent to me and determine the following:

- Am I giving up any items?
- What are the item ID's they have put in the trade

**Comment by jwigley** [comment]
The documentation [here](https://github.com/Alex7Kom/node-steam-tradeoffers#getofferoptions-callback) and [here](https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#CEcon_TradeOffer) is very clear.

Questions like this are better off being posted on the [steam forward forum](https://github.com/steam-forward/node-steam-forum). Issues are only for bugs and feature requests.

**Comment by iJamesPHP** [comment]
Thanks a lot for the help, I've got the Asset IDs being outputted now I believe, here is my code:

``
 if (offer.trade_offer_state === 2) {
        
        	offers.loadPartnerInventory({
        	    appId: '730',
        	    contextId: '2',
        	    partnerSteamId: offer.steamid_other
        	}, function(e, items, itemsraw) {
        	jamesBug('items length: '+items.length);
        	jamesBug('itemsraw length: '+itemsraw.length);
        	jamesBug('Offer response recieved, decoding...');
        	   
        	   
        	   for (var i = 0; i < items.length; i++) {
        	             if (items[i].tradable) {
        	               //if (items[i].id == item.asset_id ) {
        	                   jamesBug('Item within trade found [id]: '+items[i].id);
        	                   jamesBug('Item within trade found [no id]: '+items[i]);
        	                   jamesBug('Item within trade found [raw]: '+items[i].id);
        	                   //checkedItem = items[i];
        	                   //break;
        	               //}
        	             }
        	           }
``

When I trade offer myself 1 item I get this response output:

``
[Sun, 28 Feb 2016 01:06:56 GMT] Trade recieved.
[Sun, 28 Feb 2016 01:06:59 GMT] Offer response recieved, decoding...
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270838660
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270784739
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270784721
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270784703
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270784685
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270784675
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270661801
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270595245
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270595219
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270595181
[Sun, 28 Feb 2016 01:06:59 GMT] Item within trade found: 5270595158
``

And a whole lot more, a couple questions i have here:

- Why are there so many IDs for one item?
- How do I cross-reference this ID to the partner's inventory so that I can get the market_hash (the name)

Thanks so much,

James

**Comment by Alex7Kom** [comment]
@iJamesPHP This is not a help desk.
