### ISSUE TITLE
Please Try Again Later. (20) MakeOffer

### ISSUE THREAD

**Issue by ma1mun** [Alex7Kom/node-steam-tradeoffers#243]
Hello!

I had multiple errors till now like 15, 26, etc. but I got all of those fixed.
Now the only thing left is that it gives me error 20 and I can't seem to fix it.

When I manually add the itemsFromThem it works, but when it gets them from the variable it gives error 20.

Please help!

**Comment by Alex7Kom** [comment]
#121
