### ISSUE TITLE
Error: Disconnected occurring only on VPS

### ISSUE THREAD

**Issue by iJamesPHP** [Alex7Kom/node-steam-tradeoffers#245]
I understand that you guys HATE people posting their issued on here, but I'm totally dumbfounded at why I'm getting this error.

I have a script for handling trade offers running perfectly locally from my terminal, however, on my VPS I get the [Error: Disconnected], I've been pulling my hair out all night looking for an answer to this because I have no idea why this would be happening, thanks for any help.

**Comment by Alex7Kom** [comment]
No 'HATE', just question issues do not belong here because this is not a help desk. Besides, your question has nothing to do with `steam-tradeoffers` module anyway.
