### ISSUE TITLE
Why do we need core steam-bot for trade offers after all?

### ISSUE THREAD

**Issue by MaxYari** [Alex7Kom/node-steam-tradeoffers#247]
Hi there, can you aid my curiosity? 
— As far as i get it, trade offers work via steam web API + simulating browser with cookies to actually send offers.
— And we can use purely steam website for trade offers without a need to install client.
 
So does it makes sense that we should be able to use trade offers without need to startup steam-bot, which as i understand emulates steam client, which we dont need? 

I was looking at the source of storehouse and it seems that steam-bot itself is used only to login. And then it just sits there, eating precious RAM.

**Comment by Alex7Kom** [comment]
As said in README, `steam-tradeoffers` module **does not** depend on `node-steam`. Feel free to use any other way to obtain Steam cookies.

**Comment by MaxYari** [comment]
Can you possibly give me any idea on how to actually do this? As i
understand steam-tradeoffers have no method for optaining cookies
given username+pass. I mean maybe there is some npm module already on
your mind?

2016-03-13 19:30 GMT+03:00, Alexey Komarov <notifications@github.com>:

**Comment by andrewda** [comment]
Any module that can retrieve the Steam cookies and send them back to you would work fine. Examples of modules like this would be `node-steam` or `node-steam-user`.

**Comment by MaxYari** [comment]
Well, usage of node-steam is pretty clear, i was just wondering if its
possible to do without it. Took a look at node-steam-user, it seems to be
also more of an addition to node-steam.
Found something - was thinking about something like this
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity i.e
just pure steam web module. Not sure if there any drawbacks of using this
instead of node-steam though.
Anyways thanks for advise, and for you great module!


2016-03-13 21:13 GMT+03:00 Andrew Dassonville <notifications@github.com>:

**Comment by andrewda** [comment]
`node-steamcommunity` would work fine. Again, if you can get the cookies from it, it's all good.

**Comment by MaxYari** [comment]
Ok, sorry if I annoy you, but here's something that i'm curious about not
really realted to you module directly. I took a quick glance at source of
node-steam-weblogon and it seems that it's not using actually username+pass
to login to steamcommunity, but rather session info from log-in to steam
client. Am i correct and there is some reason behind it like bypassing some
captcha or other protection stuff, or is it made simply out of convenience,
and there is no real difference between session data login and using
username+pass. Any ideas?

2016-03-13 21:28 GMT+03:00 Andrew Dassonville <notifications@github.com>:

**Comment by Alex7Kom** [comment]
`node-steam-weblogon` was previously a part of `node-steam` and it uses the same mechanism by which the original Steam client obtains a web session, which is why it requires `node-steam` to function. The other way to obtain a web session is to emulate login to Steam Community and this is what `node-steamcommunity` does. It does not matter which way you'll use to obtain a session to use with trade offers.
I hope that resolves your confusion because I'm locking this as off-topic, also #121.
