### ISSUE TITLE
How to send offers :)

### ISSUE THREAD

**Issue by Xeroner** [Alex7Kom/node-steam-tradeoffers#248]
Hi there, i'm having a problem with offers sending.
How to for example send offer with this items ? :)

`[{"itemID":"1","itemSteamOwnerInfo":{"steamid":"76561198269216247","communityvisibilitystate":3,"profilestate":1,"personaname":"Xeroner | csbox.pl","lastlogoff":1458407539,"commentpermission":1,"profileurl":"http:\/\/steamcommunity.com\/profiles\/76561198269216247\/","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39.jpg","avatarmedium":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_medium.jpg","avatarfull":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_full.jpg","personastate":1,"realname":"Jacek jacek","primaryclanid":"103582791429521408","timecreated":1450561403,"personastateflags":512},"itemName":"SCAR-20 | Sand Mesh (Battle-Scarred)","itemPrice":"4","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopbmkOVUw7ODYTjBH_9SJh4GFk8j8NrrHj1Rd6dd2j6eTrNWm3wfiqENpNjymIY6Qdlc_YluC_wW-ku7sjcC1u87Kzndhv3Uh-z-DyCxux8v2"},{"itemID":"2","itemSteamOwnerInfo":{"steamid":"76561198086362293","communityvisibilitystate":3,"profilestate":1,"personaname":"skaju H1Z1FORUM.PL","lastlogoff":1458406871,"commentpermission":1,"profileurl":"http:\/\/steamcommunity.com\/id\/SKVJU\/","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/e7\/e7327c6c60058c9bf6786f6febff61150b608f2f.jpg","avatarmedium":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/e7\/e7327c6c60058c9bf6786f6febff61150b608f2f_medium.jpg","avatarfull":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/e7\/e7327c6c60058c9bf6786f6febff61150b608f2f_full.jpg","personastate":0,"realname":"\u0646\u0639\u0644\u0627\u0634 \u0633\u0646\u0634\u062a\u0639 \u0621\u064a","primaryclanid":"103582791440880206","timecreated":1363462077,"personastateflags":0,"loccountrycode":"AE","locstatecode":"03","loccityid":5071},"itemName":"Nova | Polar Mesh (Battle-Scarred)","itemPrice":"4","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpouLWzKjhzw8zFdC5K092kl5SClMj3PLXFhGpC_Pp5j-jX7LP5iUazrl06MG33dYWSIQI4Zw6BqAXslO29hpHvtJXIzXphuyN34S6OlxS01R1EcKUx0tPh_5jj"},{"itemID":"3","itemSteamOwnerInfo":{"steamid":"76561198269216247","communityvisibilitystate":3,"profilestate":1,"personaname":"Xeroner | csbox.pl","lastlogoff":1458407539,"commentpermission":1,"profileurl":"http:\/\/steamcommunity.com\/profiles\/76561198269216247\/","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39.jpg","avatarmedium":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_medium.jpg","avatarfull":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_full.jpg","personastate":1,"realname":"Jacek jacek","primaryclanid":"103582791429521408","timecreated":1450561403,"personastateflags":512},"itemName":"Tec-9 | Army Mesh (Field-Tested)","itemPrice":"4","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhzw8zFdC5K092kmZm0mvLwOq7cqWdQ-sJ0xLDCrIj22lXi-BA6MDr3dY_Dcw5saQvT_QW_lO-9jZK1uZrLnSdmuSE8pSGKHoGgJ0Y"},{"itemID":"4","itemSteamOwnerInfo":{"steamid":"76561198269216247","communityvisibilitystate":3,"profilestate":1,"personaname":"Xeroner | csbox.pl","lastlogoff":1458407539,"commentpermission":1,"profileurl":"http:\/\/steamcommunity.com\/profiles\/76561198269216247\/","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39.jpg","avatarmedium":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_medium.jpg","avatarfull":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_full.jpg","personastate":1,"realname":"Jacek jacek","primaryclanid":"103582791429521408","timecreated":1450561403,"personastateflags":512},"itemName":"PP-Bizon | Sand Dashed (Well-Worn)","itemPrice":"4","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpotLO_JAlfwOP3ZTxS6eOlnI-Zg8jnMrXVqWZU7Mxkh9bN9J7yjRrm8xI5ajr0IYXGclI3Z16DqVLqlb_t0MPvvc7KzCMyvyUns3ndzkTkn1gSOcRWfgr_"},{"itemID":"5","itemSteamOwnerInfo":{"steamid":"76561198269216247","communityvisibilitystate":3,"profilestate":1,"personaname":"Xeroner | csbox.pl","lastlogoff":1458407539,"commentpermission":1,"profileurl":"http:\/\/steamcommunity.com\/profiles\/76561198269216247\/","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39.jpg","avatarmedium":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_medium.jpg","avatarfull":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/9f\/9fb21a3a62bb7f7917a92dfd419b76992d3dfb39_full.jpg","personastate":1,"realname":"Jacek jacek","primaryclanid":"103582791429521408","timecreated":1450561403,"personastateflags":512},"itemName":"UMP-45 | Urban DDPAT (Minimal Wear)","itemPrice":"4","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1Jf2-r3dTlS7ciJgZKJqPv9NLPFqWdQ-sJ0xLvArdr02wa2rkJkZWyidoGSdwFqaViCrAPrlOrr1p68upvLnCdn7ik8pSGKhoReARI"}]`

**Comment by Xeroner** [comment]
I was trying 

`Bot.offers.makeOffer ({
                            partnerSteamId: winnerID,
                            itemsFromMe: item, // this is my json items
                            accessToken: WinnerTradeToken,
                            itemsFromThem: [],
                            message: 'winngs from '+sitename+' game number #'+gamenum
                        }, function(err, response){
                            if (err) {
                                console.log(err);
                                return;
                            }
                            console.log('Trade offer for queue '+gamenum+' sent!');
                        });`

**Comment by Alex7Kom** [comment]
#121
