### ISSUE TITLE
Error when sending offer

### ISSUE THREAD

**Issue by Xeroner** [Alex7Kom/node-steam-tradeoffers#251]
Hi there, what is 15 code on my error?

> There was an error sending your trade offer. Please try again later. (15)

When i'm adding this user to friend, my offer will be send. But how to solve this problem without adding every user to friend?

**Comment by Exokay88** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd

AccessDenied = 15;
no tradeoffer secret.

**Comment by andrewda** [comment]
#121

**Comment by Xeroner** [comment]
But i have tradeoffer secret...

**Comment by Exokay88** [comment]
echo ur makeoffer see what the secret string is.

**Comment by Xeroner** [comment]
`socket-0 Trade token: C8prg0wN
socket-0 [Error: There was an error sending your trade offer.  Please try again later. (15)]`

**Comment by Exokay88** [comment]
7 days steamguard otherwise

**Comment by Xeroner** [comment]
Nope, becouse when i'm adding someone it's sending.

**Comment by Exokay88** [comment]
can u paste ur send function?

**Comment by Exokay88** [comment]
steamID=row[i].userid;
						itoken=row[i].token;
						offers.makeOffer ({
							partnerSteamId: steamID,
							itemsFromMe: item,
							accessToken: itoken,
							itemsFromThem: [],
							message: 'Top kek mate. '+sitename+' #'+gamenum
						}

this is mine from the time i made my bot.

**Comment by Xeroner** [comment]
I'm sorry... i don't have token included to send function.... I meaking my own problems.... :) Thanks dude for notice :)
