### ISSUE TITLE
Problem with hold duration!

### ISSUE THREAD

**Issue by Xeroner** [Alex7Kom/node-steam-tradeoffers#252]
Why my bot is accepting offers with hold duration... 
My code :

`TradesRecived.forEach(function (value, index) {
            var tradeOwner = value.steamid_other;
            var tradeID = value.tradeofferid;
            var tradeItems = value.items_to_receive;
            var csgo = true;
            var holded = false;
            if (tradeOwner == '76561198181925605') {
                return;
            }
            if (value.items_to_receive != undefined) {
                value.items_to_receive.forEach(function (value, index) {
                    if (value.appid != '730') {
                        csgo = false;
                    }
                });
            }
            Bot.offers.getTradeHoldDuration({
                tradeOfferId: tradeID
            }, function (err, hold) {
                if (err) {
                    console.log(err);
                    console.log(tradeID);
                    declineOffer(tradeID, tradeOwner, 'hold', 'Brak');
                    return;
                } else {
                    var HisHold = hold['their'];
                    my = hold['my'];
                    their = hold['their'];
                    console.log(their);
                    if (hold['their'] == 15) {
                        holded = true;
                        declineOffer(tradeID, tradeOwner, 'hold', 'Brak');
                        return;
                        return false;
                    } else if (hold['their'] > 0) {
                        holded = true;
                        declineOffer(tradeID, tradeOwner, 'hold', 'Brak');
                        return;
                        return false;
                    } else if (hold['my'] > 0) {
                        holded = true;
                        declineOffer(tradeID, tradeOwner, 'hold', 'Brak');
                        return;
                        return false;
                    }
                }
            });`

**Comment by Xeroner** [comment]
http://pastebin.com/DbvWp9eq

**Comment by Alex7Kom** [comment]
#121
