### ISSUE TITLE
Bot can login but when gets an offer crashes...

### ISSUE THREAD

**Issue by HBMC** [Alex7Kom/node-steam-tradeoffers#259]
CONSOLE:( http://imgur.com/gNLm9XD ) Idk whats the problem 7 days cant be couse i use totp...
Maybe i am doing this wrong?

`function weblogon() {
    steamClient.webLogOn(function(newCookie) {
            offers.setup({
                    sessionID: sessionID,
                    webCookie: cookies,
                    APIKey:           '2BD989okjusttonotgetfuckedD86EF3F1'
            }, function(err) {
                    if (err) {
                    }
            });
    });
}`

**Comment by Alex7Kom** [comment]
Make sure you do any library calls after `setup()`.
