### ISSUE TITLE
Offers.setup() causes script to freeze

### ISSUE THREAD

**Issue by Axumata** [Alex7Kom/node-steam-tradeoffers#267]
node-steam-tradeoffers version 3.0.2
Node.js version is 4.4.4
Script freezes on calling setup() method, no error is thrown and callback function never fires.

**Comment by jwigley** [comment]
What script freezes? You haven't posted any code.

**Comment by Axumata** [comment]
nvm I'm being stupid. The problem was that there shouldn't be any callback.
