### ISSUE TITLE
getOfferToken is broken

### ISSUE THREAD

**Issue by TrueCarry** [Alex7Kom/node-steam-tradeoffers#273]
Apparently steam broke https://steamcommunity.com/my/tradeoffers/privacy this url, so you should use full one now.
I've changed my local code to 
```js
SteamTradeOffers.prototype.getOfferToken = function(steamid, callback) {
  if(typeof steamid == 'function') {
    callback = steamid;
    steamid = null;
  }
  this._request.get({
    uri: communityURL + (steamid
        ? `/profiles/${steamid}/tradeoffers/privacy`
        : `/my/tradeoffers/privacy`)
```
Not sure if it's best way to handle this, but it works.

**Comment by Alex7Kom** [comment]
It also works with plain HTTP http://steamcommunity.com/my/tradeoffers/privacy which makes me think that it is a misconfiguration of their CDN. So I'd like to wait a bit before making any changes to the library.
