### ISSUE TITLE
Don't accept tradeoffers

### ISSUE THREAD

**Issue by Kasp42** [Alex7Kom/node-steam-tradeoffers#274]
![Code](https://0sc.ru/XCdZlcFtG7)

At first it was
![Console](https://0sc.ru/lMv40KBNFs)
And now
![Console](https://0sc.ru/71KRS4DgEl)

**Comment by tambu22** [comment]
28 means 2 things:

1> items not available
2> steam is not working good so it load Empty offers.

**Comment by andrewda** [comment]
@tambu22 the latter is the most likely reason at the moment. Steam seems to be sending error 28 much more often than normal.
