### ISSUE TITLE
[FEATURE REQUEST] Get an "In-Trade" flag per each item on load my invnetory

### ISSUE THREAD

**Issue by tambu22** [Alex7Kom/node-steam-tradeoffers#276]
tittle just say all, ll be good if the method get my inv can check if the items are in trade, and add som like "InTradeItems: false" and dont get the items that are in a active or waiting mobile Trade. 

tnks!

**Comment by andrewda** [comment]
This would require something like node-steam-tradeoffer-manager's `polldata.json`. However, this repository is meant to be more of a wrapper for Steam's API, so this wouldn't really be within the scope of this library. It would be pretty easy to write your own, though.

**Comment by Alex7Kom** [comment]
As @andrewda said, this is outside the scope of the library.
