### ISSUE TITLE
Issue or steam bugged out?

### ISSUE THREAD

**Issue by MaxYari** [Alex7Kom/node-steam-tradeoffers#278]
Can't get offer token via `getOfferToken` - always returns 429, even if I retry after a minute. 
Method attempts to get `https://steamcommunity.com/my/tradeoffers/privacy`, interestingly enough, I can't reach this link via browser also (blank white page).
Use of `http` link instead of `https` works with both browser and your module.

**Comment by Alex7Kom** [comment]
Yes, and the library was already updated to use HTTP link. See #273.

**Comment by MaxYari** [comment]
Oh, ok, grabbing update then, thanks for a great module, Alex!
