### ISSUE TITLE
Issue logging in with multiple accounts

### ISSUE THREAD

**Issue by rkiernan** [Alex7Kom/node-steam-tradeoffers#280]
Logging into the bot with one account works fine, but then when I change the login information, logging in with other accounts is impossible. I receive the email that there has been a login attempt from a new computer, but I continue failing the login and receiving this email after updating the auth code. However, I am still able to log in with the first account information I used. Is this a bug or a normal part of the bot?

**Comment by Alex7Kom** [comment]
Logging into Steam has nothing to do with `node-steam-tradeoffers`.
#121
