### ISSUE TITLE
TypeError: str.indexOf is not a function

### ISSUE THREAD

**Issue by woolfi182** [Alex7Kom/node-steam-tradeoffers#283]
Cheers,
I use node-steam-tradeoffers, which use a long library
I tried to run `steamTrade.loadPartnerInventory` function but had an error instead:

```
steamTrade.loadPartnerInventory({
                partnerSteamId: 184774529,
                appId,
                contextId,
                language: language
            }, (err,inv,curr)=> { ...});
```

> TypeError: str.indexOf is not a function
> at Function.fromString (.../node_modules/long/dist/long.js:260:22)
> at toAccountId (.../node_modules/steam-tradeoffers/index.js:374:15)

I wrote about this trouble to [Long issues #37 ](https://github.com/dcodeIO/long.js/issues/37)
Think, you must know that

**Comment by Alex7Kom** [comment]
You pass an account id (which is a `Number`, which is why Long crashes). You should pass account id as `partnerAccountId`. `partnerSteamId` is 64-bit SteamID (a `String`).

**Comment by woolfi182** [comment]
thanks, but it doesn't work too:
```
steamTrade.loadPartnerInventory({
                partnerSteamId: 76561198145040257,
                appId:730,
                contextId:2
            }, (err,inv,curr)=> { ...});
```

> Error: missing required parameter

I tried to do other things, like
- partnerAccountId : 184774529
- partnerAccountId : 'STEAM_0:1:92387264'

I set one of an above things, but it doesn't help me

Other info:
- profile I use is private one
- profile by whom I connected to is public 
- these two are not friends

**Comment by Alex7Kom** [comment]
As I said, it should be a `String`:

```js
steamTrade.loadPartnerInventory({
    partnerSteamId: '76561198145040257',
    appId: 730,
    contextId: 2
}, (err,inv,curr)=> { ...});
```

**Comment by Alex7Kom** [comment]
> Error: missing required parameter

Also make sure you initialize the library correctly and your session is valid.

**Comment by woolfi182** [comment]
I sent it as a Number and as a String, but results were the same.

> Error: missing required parameter

I tried to get data from url: 
http://steamcommunity.com/profiles/76561198145040257/inventory/json/570/2 and it was Ok

Than, I researched query built your library and was supprised, it was something like this:
uri: https://steamcommunity.com/tradeoffer/new/partnerinventory/?sessionid=&partner=76561198145040257&appid=570&contextid=2
referer: https://steamcommunity.com/tradeoffer/new/?partner=184774529

So, when I pasted the above uri in a browser I had this:
> {"success":false,"error":"missing required parameter"}

I think that referer needs accessToken

**Comment by woolfi182** [comment]
> Also make sure you initialize the library correctly and your session is valid.
I'm sure that session is valid, because I can get my inventory, but cannot get partner account

**Comment by Alex7Kom** [comment]
Make sure you setup `sessionID` correctly in `setup()`, because `sessionid` is missing in URL you provided above.

**Comment by woolfi182** [comment]
Thanks a lot, it works clearly
It was my fault, I wrote `sessionId` instead of `sessionID`.
