### ISSUE TITLE
'ETIMEDOUT' while sending tradeoffer.

### ISSUE THREAD

**Issue by hell00world** [Alex7Kom/node-steam-tradeoffers#284]
Hello, i have got that error, while sending trade. Sometimes it's sends a tradeoffer, but usually no.

```
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false }
Error: ETIMEDOUT
    at null._onTimeout (node_modules/steam-tradeoffers/node_modules/request/request.js:759:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

What to do?

**Comment by Alex7Kom** [comment]
Retry your request, `ETIMEDOUT` means your request is timed out. If you keep getting this error, you should troubleshoot your connection to Steam servers.

Also, #121.
