### ISSUE TITLE
Function getItems return "0" items

### ISSUE THREAD

**Issue by kregielpl** [alex7kom/node-steam-tradeoffers#291]
Hi,

Recently I've noticed that very often function "getItems" returns "0" or not all of the trade items.
I don't know what happened exactly because some time ago everything works perfectly.
Does anyone of you also meet this problem?

Thanks for reply.

**Comment by WuPei** [comment]
same here

**Comment by dvdx95** [comment]
try if(tradedata.length === 0){
//do something
}
