### ISSUE TITLE
Error: There was an error sending your trade offer.  Please try again later. (8)

### ISSUE THREAD

**Issue by maruo34** [Alex7Kom/node-steam-tradeoffers#294]
I'm trying to send a trade, but this error occurs. In what cases can this happen?

>

```
var tradeLink = url.parse(trades[key].user_trade_link, true);
                offers.makeOffer({
                    partnerAccountId: tradeLink.query.partner,
                    accessToken: tradeLink.query.token,
                    itemsFromMe:  [
                    				{"appid":730,"contextid":2,"amount":1,"assetid":"10084166636"},
                    				{"appid":730,"contextid":2,"amount":1,"assetid":"9994955518"},
                    				{"appid":730,"contextid":2,"amount":1,"assetid":"9994950194"}
                    			],
                    itemsFromThem: [],
                    message: config.domain
                }, function(err, response) {
                    if (err) {
                        console.log(err); 
                    } else {
                        changeStatusTrade(trades[key].uid,1); 
                        AcceptMobileOffer(trades[key].uid);
                    }
                });
```

**Comment by andrewda** [comment]
(in the future, please ask questions on the node-steam-forums repository, per #121)

Here's a description of the error you're getting: https://steamerrors.com/8

Some parameter you're sending to Steam isn't right. Try logging your `tradeLink.query.partner` and `tradeLink.query.token` to make sure they're correct. Another possible source of error could be that you're specifying an `amount` in the item objects – that isn't necessary for basically anything besides Spiral Knights Currency so try removing that. Also, `itemsFromThem` is not needed if it's just empty, so you should be able to remove that.
