### ISSUE TITLE
Error when making an offer

### ISSUE THREAD

**Issue by AndrewRAN** [Alex7Kom/node-steam-tradeoffers#296]
My code:
`var Steam = require('steam');
var SteamWebLogOn = require('steam-weblogon');
var SteamTotp = require('steam-totp');
var getSteamAPIKey = require('steam-web-api-key');
var SteamTradeOffers = require('steam-tradeoffers');

var logOnOptions = {
  account_name: 'mylogin',
  password: 'mypassword',
  two_factor_code: SteamTotp.generateAuthCode('AVBpV71j0Ds0smNih9FfHEbQuxk=')
};

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
var offers = new SteamTradeOffers();

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn(logOnOptions);
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult === Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online);
    steamWebLogOn.webLogOn(function(sessionID, newCookie) {
      getSteamAPIKey({
        sessionID: sessionID,
        webCookie: newCookie
      }, function(err, APIKey) {
        offers.setup({
          sessionID: sessionID,
          webCookie: newCookie,
          APIKey: APIKey
        });
        //write here ../
        offers.makeOffer ({
        partnerSteamId: mypartnersteamid,
        accessToken: "tradetoken",
        itemsFromMe: [
          {
            appid: 730,
            contextid: 2,
            amount: 1,
            assetid: 10639479325
          }
        ],
        itemsFromThem: [],
        message: 'test'
      }, function(err, response) {
        if (err) {
          throw err;
        }
        console.log(response);
      });;
      });
    });
  }
});`

And it returns this error:

![screenshot_1](https://user-images.githubusercontent.com/23475741/27275998-16b5f224-54f3-11e7-953b-2a70cff6859a.png)

**Comment by Alex7Kom** [comment]
Make sure `mypartnersteamid` is a SteamID64 string.

**Comment by AndrewRAN** [comment]
Я так понял, вы русский?

**Comment by AndrewRAN** [comment]
Ugh, when sendind a trade offer there is a steam error 26. What can I do?

**Comment by andrewda** [comment]
https://steamerrors.com/26

> This response code suggests that one or more of the items in this trade offer does not exist in the inventory from which it was requested.

**Comment by AndrewRAN** [comment]
Ugh, I really don't understand... The item exists in my inventory.

**Comment by AndrewRAN** [comment]
http://steamcommunity.com/id/cubsonyt/inventory/#730_2_10784182205
`offers.makeOffer ({
        partnerSteamId: '76561198000501285',
        accessToken: "RXCnxaDn",
        itemsFromMe: [
          {
            appid: 730,
            contextid: 2,
            amount: 1,
            assetid: 10573181929
          }
        ],
        itemsFromThem: [],
        message: 'test'
      }, function(err, response) {
        if (err) {
          throw err;
        }
        console.log(response);
      });`

**Comment by AndrewRAN** [comment]
OMG, assetid needs to be in ""...
