### ISSUE TITLE
getItems(options, callback)

### ISSUE THREAD

**Issue by vifus** [alex7kom/node-steam-tradeoffers#299]
api.get('/getOffer/:offerTradeId', function (req, res) {
        offers.getOffer({"tradeofferid": req.params.offerTradeId}, function(err, offerResponse) {
            if(err){
                console.log(err);
            } else {
                offers.getItems({
                    tradeId: offerResponse.response.offer.tradeid
                }, function(error, tradedata) {
                    if (!error) {
                        console.log('TradeData');
                        console.log(tradedata);
                    } else { console.log(error); }
                });
            }
        });
    });

And after i run /getOffer/tradeid... is error: "Error: No session" i dont have idea what is going on.

Start session code:

    client.on("webSession", function(steamID, cookies){
        console.log("[+]Posiadamy ciastka");
        console.log("[+]Przygotowywujemy sesje");
        var sessionID = cookies[0].split("=")[1];
        console.log("[+]Posiadamy sesje: "+sessionID);
        offers.setup({
          sessionID: sessionID,
          webCookie: cookies,
          APIKey: webAPIKey
        });
        community.setCookies(cookies);
        community.startConfirmationChecker(pollingTime, identitySecret);
    });

**Comment by irqize** [comment]
The reason why it happens is your using tradeofferid instead of tradeid, which you get after accepting the trade.
