### ISSUE TITLE
Session expiring / 401 errors

### ISSUE THREAD

**Issue by blindinglt** [Alex7Kom/node-steam-tradeoffers#45]
After I start my app and process several transactions (grabbing inventory, sending trades, etc.) my session suddenly "breaks" and I start getting 401's whenever I try to interface with Steam. There's no clear pattern that I can find, but it always happens pretty quickly after starting the app and processing transactions.

Here's an example of the error I get (I've just appended the error code at the end):

Nov 12 11:32:37 hidden-reaches-4324 app/web.1: ERROR LOADING INVENTORY: https://steamcommunity.com/tradeoffer/new/partnerinventory/?sessionid=NjEyODA3MTI1&partner=76561198027075040&appid=440&contextid=2 - 401

From what I can gather, a 401 error means my Steam session is no longer valid. Since a Session ID is being passed, it must be that Steam is invalidating my session. The only thing that fixes it is relogging in and getting a new Session ID.

It doesn't happen locally, as far as I can tell, but on my Heroku instance it happens all the time. Any idea what could be happening or how I can debug further?

**Comment by JasonPaulos** [comment]
@srabouin When you said, "every other error would just result in a retry anyway," do you mean that node-steam-tradeoffers automatically retries, or that we should trigger a retry with our implementations?

**Comment by CodeLuca** [comment]
@Alex7Kom How do we renew a dead session?

**Comment by scholtzm** [comment]
Call `webLogOn` (or whatever is the name of the function in your lib to retrieve the cookies) again.
