### ISSUE TITLE
It's possible to get BOT trade token?

### ISSUE THREAD

**Issue by Maxpain177** [Alex7Kom/node-steam-tradeoffers#56]
For example can parse ```http://steamcommunity.com/id/me/tradeoffers/privacy``` page for retrieve #trade_offer_access_url, like a getAPIKey function, that retrieve steam api key.

**Comment by Alex7Kom** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers#getoffertokencallback

**Comment by Maxpain177** [comment]
thx
