### ISSUE TITLE
There was an error sending your trade offer.  Please try agai n later. (26)

### ISSUE THREAD

**Issue by ronjunelopez** [Alex7Kom/node-steam-tradeoffers#57]
There was an error sending your trade offer.  Please try agai
n later. (26)

**Comment by pmk010** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd

Error

**Comment by khodzha** [comment]
this error is also returned if you try to send trade offer with non tradable item

**Comment by insanesvk** [comment]
This popped up just recently, I can confirm that it happened to my bots with "non tradable items" aka. items that got trade locked.

**Comment by l419351633** [comment]
i can offer a normal trade with some items through the steam client or the steam web, but this will pop up when i try with the bot.i checked the item id, those short can be trade correctly.the status code of the response is 401.this only goes wrong for some specific items.

**Comment by insanesvk** [comment]
@l419351633 Did you actually wait for the one week period (after creating the sentry files on your server)?

**Comment by HelloErrybody** [comment]
Do you have to wait 7 days for the bot to be able to send trade offers? Same thing that happens if you log into a steam account on a new webbrowser / new computer?
