### ISSUE TITLE
KeyBanking Bot

### ISSUE THREAD

**Issue by spyfly** [Alex7Kom/node-steam-tradeoffers#66]
Has anyone an example for an keybanking bot? I'm not so experienced with coding in Node.js. I don't know how I can do this. Any examples?

**Comment by pmk010** [comment]
Well you can find some examples by googling, looking on pastebin etc. However I learnt through looking through the basic examples provided with node-steam* and trial and error. It would help if you first understood the basics of node.js with callbacks and everything else.
