### ISSUE TITLE
Trade Confirmation

### ISSUE THREAD

**Issue by Alex7Kom** [Alex7Kom/node-steam-tradeoffers#68]
By default now, trade offer which move items from your account must be confirmed by email.

![inbox 29891 messages 9 unread 2015-01-21 09-10-40](https://cloud.githubusercontent.com/assets/181961/5831953/c23f9264-a14d-11e4-9c21-1b89e2e51d8d.png)

You can disable this in http://steamcommunity.com/my/edit/settings/

![steam 2015-01-21 09-11-23](https://cloud.githubusercontent.com/assets/181961/5831968/01985388-a14e-11e4-8cdb-85b7d1f8442d.png)

EDIT: I plan to support Trade Confirmation as a separate module in the near future.

**Comment by filsmick** [comment]
Hi. May I know how you intend to support this new feature? Will you add the ability to enable or disable it programmatically, or something else?

**Comment by Alex7Kom** [comment]
It will be an ability to connect to email account and confirm trades using confirmation codes sent by Steam. However, It doesn't seem to be secure, since now you'll need to store email account data along with Steam credentials, so I think of better ways how to do this.
I didn't plan to implement disabling/enabling confirmations programmatically, is it needed?

**Comment by scholtzm** [comment]
Is the support really needed? Seems like an overkill to me.
Disabling it once is a straight-forward task (although tedious if you own many accounts).

**Comment by filsmick** [comment]
I agree with @scholtzm. Adding email confirmation seems way outside the scope of this module. Users should get an email client like https://github.com/mscdex/node-imap to do the job.

**Comment by Alex7Kom** [comment]
Thank you for suggestions! Yes, having a separate module for this makes sense, since we don't need any parts of `steam-tradeoffers` for confirmations to function. This way it can be run not only in a different process, but on a different server without access to Steam credentials so it will be more secure than having all in one place.

**Comment by Alex7Kom** [comment]
So we came to conclusion that Trade Confirmation is out of the scope of `steam-tradeoffers` module.
