### ISSUE TITLE
`.getOffer` returns "undefined" on first attempt

### ISSUE THREAD

**Issue by andrewda** [Alex7Kom/node-steam-tradeoffers#72]
When `.getOffers` is first called here the application breaks because it returns `undefined` for the body variable. The solution for my code is to add an if statement verifying that body is not undefined, but it seems to be a bug none the less.
```
offers.getOffers({
  get_sent_offers: 1,
  active_only: 0,
  time_historical_cutoff: Math.round(Date.now() / 1000)
}, function(error, body) {
  body.response.trade_offers_sent.forEach(function(offer) {
    console.log("OFFER: " + offer.tradeofferid);
    if (offer.trade_offer_state == 3) {
      console.log("> accepted");
    } else {
      console.log("> not accepted");
    }
  });
});
```

**Comment by Alex7Kom** [comment]
If `body` is undefined then `error` most likely does contain an error and you should check it.

**Comment by andrewda** [comment]
I seem to be getting the error `[Error: 403]`
