### ISSUE TITLE
Convert "accountid_other" to community id

### ISSUE THREAD

**Issue by pmk010** [Alex7Kom/node-steam-tradeoffers#73]
I wanted to know if there was a way of converting the "accountid_other" parameter of a trade offer to a community id.

A quick google search threw nothing up, so any help would be appreciated.

Many thanks

**Comment by pmk010** [comment]
Realised I could dive into index.js and find it myself. For anyone who is interested:
Long(parseInt(accountId, 10), 0x1100001).toString()

**Comment by Alex7Kom** [comment]
You are looking for `steamid_other` property which added automatically to trade offers in responses of `.getOffer` and `.getOffers`.
