### ISSUE TITLE
Error: There was an error sending your trade offer.  Please try again later. You cannot trade with XXXX. (50)

### ISSUE THREAD

**Issue by IMhide** [Alex7Kom/node-steam-tradeoffers#76]
Hi, Sorry if my english is not perfect it's not my native language.

So I tried to understand and use this NPM. But my knowledge in the Steam API is pretty restricted.
I used your offerbot.js. Change it a little bit to work with CS:GO items.

I can load mine and my partner's Inventory. So I think that i've made everything right. But when I try to makeOffer I've this damn error : 

Error: There was an error sending your trade offer.  Please try again later. You cannot trade with XXXX. (50)

I searched on Google, some peoples are saying that it's a cookie related issue. But nothing clear.

Can you help me ?

**Comment by andrewda** [comment]
Possible solution: http://steamcommunity.com/app/440/discussions/0/619568793770743820/

**Comment by blanko18** [comment]
Base on my experience this happens either when you try to bet an item that is already gone or your account has 5 more pending trade offers

**Comment by david500834** [comment]
I think we can absolutely know the "err:50" is causede by "5 more pending" thankyou @blanko18
