### ISSUE TITLE
Feature Request : Check if a trade offer has been completed.

### ISSUE THREAD

**Issue by JakeCooper** [Alex7Kom/node-steam-tradeoffers#77]
There might be something like this already, but It would be great if I had a way to check if the trade offer I sent was completed. Adding a callback for it would be fantastic.

**Comment by andrewda** [comment]
I use this code to check if an offer is complete:
```
    setInterval(function(){
        offers.getOffer({
            "tradeofferid": XXXXXXXXX // The tradeoffer id
        }, function(error, body) {
            if (error == null) {
                if (body.response.offer.trade_offer_state == 3) {
                    //on trade offer accepted
                } else {
                    //on not accepted
                }
            }
        });
    }, 5000);
```
It checks if the trade offer is accepted every 5 seconds, and if it is, runs the code.

**Comment by Alex7Kom** [comment]
This is not going to be implemented, because Steam Web API does not have any push capabilities. Poll Steam Web API in your own code.
