### ISSUE TITLE
offers.loadMyInventory() doesnt return an array of items.

### ISSUE THREAD

**Issue by RakouskyS** [Alex7Kom/node-steam-tradeoffers#79]
I understand that it will only return an array of items on success, I dont know the error though.

> steam.on('tradeOffers', function(number) {
    offers.loadMyInventory({
        appId: 730,
        contextId: 2
    }, function(err, items) {
        // Getting number of keys
        // items doesnt return any array.
        for (var i = 0; i < items.length; i++) {.......

I also setup the trade offers before(?), not sure if this is being run before.

> steam.on('webSessionID', function(id) {
    steam.webLogOn(function(newCookie) {
        offers.setup({
            sessionID: id,
            webCookie: newCookie
        });
    });
});

**Comment by Ax6** [comment]
are you trying to get tf2 inventory? In this case your problem is the appid, which is 440 for tf2.

**Comment by RakouskyS** [comment]
@Ax6 Nope, its for csgo, thats 730 afaik.

**Comment by Ax6** [comment]
Then I'm not sure where the problem is, have you already tried console logging the raw item list returned by loadMyInventory?

**Comment by scholtzm** [comment]
Most importantly, you should be checking the `err` value in the `loadMyInventory` callback.

**Comment by RakouskyS** [comment]
@Ax6 @scholtzm Interesting! Seems like steam went down or something, now its all working again, items returns an array of all items. Kinda odd, but ill get a fix out so my bot doesnt crash everytime steam goes down.
