### ISSUE TITLE
403 on getOffers

### ISSUE THREAD

**Issue by JakeCooper** [Alex7Kom/node-steam-tradeoffers#81]
So I am able to getOffers when I run my brothers account (Which has games, playtime, etc), but when I run my bots, I get this 403 error.

Seems to be related to these, but I've tried everything suggested:

https://github.com/Alex7Kom/node-steam-tradeoffers/issues/32
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/48

Here's my code

    function getData() {
              var setTimer = setTimeout(getData, 10000);
              if (Date.now() - start > 300000){
                steamOfferObj.cancelOffer({
                  tradeOfferId: data["tradeofferid"]
                }, function(){
                  clearTimeout(setTimer);
                  eventEmitter.emit('requestOfferExpired');
                  return;
                })
                
              }
              steamOfferObj.getOffer({
                  "tradeOfferId": data["tradeofferid"] // The tradeoffer id
              }, function(error, body) {
                  console.log(body);
                  console.log(error);
                  if (error == null) {
                    //console.log(body);
                    console.log(body.response.offer.trade_offer_state);
                      if (body.response.offer.trade_offer_state == 3) {
                          eventEmitter.emit('requestOfferAccepted');
                          clearTimeout(setTimer);
                          return "Offer Accepted" //on accept
                      } else if(body.response.offer.trade_offer_state == 7){
                          eventEmitter.emit('requestOfferExpired');
                          clearTimeout(setTimer);
                          return "Offer cancelled";
                      } else {

                      }
                  }
              });
            }

**Comment by andrewda** [comment]
I was getting a 403 error a while ago. I found that this is occurs when you attempt to send a steam message or trade offer before being successfully logged in. Try having your program wait 5 seconds before getting offers and see if that works.

**Comment by JakeCooper** [comment]
Well thing is, I can send tradeOffers fine, I just can't pole the offer using the getOffer command, so I don't think its an issue of not being signed in.

**Comment by andrewda** [comment]
Yes that is strange. I'll try your code any see what happens for me. It could just be that the steam inventory servers are down or slow at he moment.

**Comment by JakeCooper** [comment]
But also weird, because my alt account works, but not the bots.

**Comment by andrewda** [comment]
I think I found your issue. When I used your code with a random string of numbers for the tradeOfferId, i too got an error 403. However, after using a tradeOfferId that I had just sent, I received the correct output. 

My guess is that you are trying to use the same tradeOfferId as your alt account with your bots. Your bots can only check their own trade offers, so try using a tradeOfferId that your bot has and see if that works.

**Comment by JakeCooper** [comment]
The trade offer ID is generated in the callback for the makeOffer call.

 steamOfferObj.makeOffer({
            partnerSteamId : steamID,
            accessToken : userAccessToken,
            itemsFromMe: '{}',
            itemsFromThem: objectArray
          }, function(err, data) {
            console.log(err);
            console.log(data);
            var start = Date.now();
            
            function getData() {
              var setTimer = setTimeout(getData, 10000);
              if (Date.now() - start > 300000){
                steamOfferObj.cancelOffer({
                  tradeOfferId: data["tradeofferid"]
                }, function(){
                  clearTimeout(setTimer);
                  eventEmitter.emit('requestOfferExpired');
                  return;
                })
                
              }
              steamOfferObj.getOffer({
                  "tradeOfferId": data["tradeofferid"] // The tradeoffer id
              }, function(error, body) {
                  console.log(body);
                  console.log(error);
                  if (error == null) {
                    //console.log(body);
                    console.log(body.response.offer.trade_offer_state);
                      if (body.response.offer.trade_offer_state == 3) {
                          eventEmitter.emit('requestOfferAccepted');
                          clearTimeout(setTimer);
                          return "Offer Accepted" //on accept
                      } else if(body.response.offer.trade_offer_state == 7){
                          eventEmitter.emit('requestOfferExpired');
                          clearTimeout(setTimer);
                          return "Offer cancelled";
                      } else {

                      }
                  }
              });
            }

            getData();

          })

**Comment by andrewda** [comment]
Try outputting that tradeOfferId to the console and make sure it looks reasonable. I'm almost sure it has to do with some error with the tradeOfferId

**Comment by JakeCooper** [comment]
http://i.imgur.com/HCOV2Ys.png

Seems reasonable to me.

**Comment by andrewda** [comment]
Yep, that does seem fine. Here's the code I used to try and imitate what I saw in your code:

1. Works fine:
```
function getData() {
  setTimeout(function () {
    offers.getOffer({
      "tradeOfferId": "364875551" // Real tradeofferid
    }, function(error, body) {
      console.log(body);
      if (error == null) {
        //console.log(body);
        console.log(body.response.offer.trade_offer_state);
        if (body.response.offer.trade_offer_state == 3) {
         return "Offer Accepted" //on accept
        } else if(body.response.offer.trade_offer_state == 7){
          return "Offer cancelled";
        } else {
          // do something
        }
      } else {
        console.log(error);
      }
    });
  }, 5000);
}
```

2. Doesn't work:
```
function getData() {
  setTimeout(function () {
    offers.getOffer({
      "tradeOfferId": "123456789" // Random numbers
    }, function(error, body) {
      console.log(body);
      if (error == null) {
        //console.log(body);
        console.log(body.response.offer.trade_offer_state);
        if (body.response.offer.trade_offer_state == 3) {
         return "Offer Accepted" //on accept
        } else if(body.response.offer.trade_offer_state == 7){
          return "Offer cancelled";
        } else {
          // do something
        }
      } else {
        console.log(error);
      }
    });
  }, 5000);
}
```

For testing purposes, try using one of those with `data["tradeofferid"]` and see if that works.

**Comment by andrewda** [comment]
This seems to work perfectly for me:
```
function getData() {
  setTimeout(function () {
    offers.makeOffer({
      partnerSteamId: "76561198092490523",
      itemsFromMe: [
        {
          "appid": 440,
          "contextid": 2,
          "amount": 1,
          "assetid": "3585401379"
        }
      ],
      itemsFromThem: {}
    }, function(err, data) {
      console.log(data);
      console.log(err);
      offers.getOffer({
        "tradeOfferId": data["tradeofferid"] // The tradeoffer id
      }, function(error, body) {
        console.log(body);
        console.log(error);
        if (error == null) {
          //console.log(body);
          console.log(body.response.offer.trade_offer_state);
            if (body.response.offer.trade_offer_state == 3) {
                return "Offer Accepted"; //on accept
            } else if(body.response.offer.trade_offer_state == 7){
                return "Offer cancelled";
            } else {
              //do something
            }
        }
      });
    });
  }, 5000);
}
```

http://i.imgur.com/L3HH5rw.png

**Comment by JakeCooper** [comment]
What did you change there?

**Comment by andrewda** [comment]
I didn't change much there. It seems, though, that the error is on the bot's side. Have you disabled email confirmation for the bot? Has it been logged in from your Node-Steam for at least 7 days?

**Comment by JakeCooper** [comment]
The trade requests seem to send off fine, I just can't poll the trades. It's incredibly odd. Bots have a scraper that activates when the email comes in and auto verifies the trade, and the trades seem to send out fine so its not that, or the 7 day thing.

Spent a couple hours last night trying to tweak it but came up dry.

**Comment by andrewda** [comment]
Very odd. Hopefully someone more knowledgeable can shed some light on this.

**Comment by l419351633** [comment]
I think i found the reason for 403 problem.
it's related to the apikey. The getOffer or getOffers method do not get apikey for you. You need to call SteamTradeOffers.prototype.getAPIKey for youself before you call the getOffer.
Anyway,this solve my 403 problem.

**Comment by Alex7Kom** [comment]
@l419351633 There is no `SteamTradeOffers.prototype.getAPIKey` and never was, what version you are using? `getAPIKey` function is not exposed to users.

**Comment by l419351633** [comment]
@Alex7Kom When I was using 1.0.3 version, the 403 problem was fixed by the getAPIKey.
And i thought the 403 problem should be related to the apikey issues.
And apikey relates to the account. So that different accounts show different results.

**Comment by Yashko** [comment]
I have same problem with code from example (storehouse.js).
can someone help me?
![41bc76c02de134a9b855d2d53681921e](https://cloud.githubusercontent.com/assets/4582615/7491585/4b39ba0c-f3f3-11e4-8e29-1ed42d597f98.png)
