### ISSUE TITLE
Get all AssetID's of all keys in inventory

### ISSUE THREAD

**Issue by andrewda** [Alex7Kom/node-steam-tradeoffers#82]
How could I get the AssetID of all keys in my inventory? I'm looking to simply send a trade offer with this key to another user.

**Comment by RakouskyS** [comment]
use the loadMyInventory function, then pass it through a foreach loop that checks if the classID(!) is equal to the one of a key. I guess you know what to do from that on.

**Comment by andrewda** [comment]
Thanks @RakouskuS . I managed to do this a few weeks ago using `.filter` and it's been working miracles.

**Comment by RakouskyS** [comment]
Glad you found a solution, I would suggest closing this issue :)
