### ISSUE TITLE
Error 15

### ISSUE THREAD

**Issue by Glutch** [Alex7Kom/node-steam-tradeoffers#84]
Hi. I've been getting error 15 for about 3 weeks when trying to send trade offers with the bot.

> Have tried 2 different accounts (both have had sentry file for over 2 weeks)
> Have tried to send trade offer to 3 different steam accounts, same error every time.
> The inventories are not full. (Not even close)
> Both bots/accounts have steam guard enabled
> Both bots/accounts have CSGO bought (if this would matter)
> Accepting trades works fine and everything else so far.
> Edit: Code works on 1/3 account now
> assetid is correct

```
var items = [
	{
		appid: 730,
		contextid: 2,
		amount: 1,
		assetid: '1904276996'
	}
]

offers.makeOffer({
	partnerAccountId: 43941343,
	accessToken: 'oFgV2mg5',
	itemsFromMe: items,
	itemsFromThem: [],
	message: 'Oh but hi'
}, function(err, data) {
	console.log(err)
	// [Error: There was an error sending your trade offer.  Please try again later. (15)]
})
```
Any help would be extremely helpful.

**Comment by blanko18** [comment]
Base on my experience this happens either when you try to bet an item that is already gone or your account has 5 more pending trade offers
