### ISSUE TITLE
cancelOffer doesn't work

### ISSUE THREAD

**Issue by l419351633** [Alex7Kom/node-steam-tradeoffers#85]
Calling cancelOffer will get an empty response like this
```json
{
	"response": {

	}
}
```
I tried to call the web API CancelTradeOffer (v1) by Send HTTP tool and got the same response.
Is that means the API has been broken and we can't use this method?

**Comment by Alex7Kom** [comment]
Does it cancel the offer you called it for? Steam Web API is a mess and I warn in README that you shouldn't expect any meaningful response from this method.

**Comment by l419351633** [comment]
@Alex7Kom it doesn't cancel the offer.
And it doesn't return any error.
I have read the README and I thought at least the offer can be canceled.
I don't understand if this API doesn't work why it exsits.

**Comment by Alex7Kom** [comment]
Thank you, I'll investigate.

**Comment by scholtzm** [comment]
Are you cancelling an offer which *you* have sent? You can't decline offers with this function.

**Comment by MStruntze** [comment]
cancelOffer works fine for me. Haven't checked the return object but the offer is cancelled.

**Comment by l419351633** [comment]
I found the reason, thanks for all the help.
I have passed wrong parameter to the cancelOffer. 
The response object from makeOffer is 
{tradeofferid:xxxxxxx}
, but the cancelOffer need 
{tradeOfferId:xxxxxxx}.
When I pass the right object to the cancelOffer, the method will work. 
The offer has been cancelled correctly. But still return 
{
    "response": {

    }
} 
Hope this will help other careless people just like me.

**Comment by blanko18** [comment]
Hi i still cant decline/cancel the offers even though i followed the correct building of parameter

These are my code: where tradeofferidA -> is the tradeofferid

var params2 = {
                tradeOfferId:tradeofferidA
            }

  offers[rows[0].bot_steam_id].declineOffer(params2, function (err, callback) {
                         if (err) 
                         {
                            console.log("Cancel offer ERROR: " + err);
                         }
                         else
                         {
                                  if (Object.keys(callback).length > 0) 
                                  {
                                    console.log("Cancel offer with callback");
                                    console.log(callback);                                   
                                  }
                                  else
                                  {
                                    console.log("Callback error");
                                  }
                         }
                        }); 


If i display the params2 via console.log it is displayed as something like this
{ tradeOfferId: '428073619' }


Kindly help urgent
