### ISSUE TITLE
IEconService Item descriptions

### ISSUE THREAD

**Issue by RakouskyS** [Alex7Kom/node-steam-tradeoffers#86]
If I have the classid of a single item, how do I get the description / Name of the item?
Theres [this](https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService) but I do not understand how to get a value out of "descriptions" for a specific classid.

**Comment by l419351633** [comment]
Maybe you could store the descriptions with classid locally.

**Comment by RakouskyS** [comment]
@l419351633 that would be an awful lot of work, since theres a ton of skins with a ton of exteriors, and I am not looking to write down several thousands of items manually.

**Comment by l419351633** [comment]
@RakouskyS I mean basically when you acquire the classid of the item, you should get the description with it. Maybe there are better ways to approach this, like getting the description through the market.

**Comment by RakouskyS** [comment]
@l419351633 My problem is I cant find items on the market with the classid afaik.

**Comment by Spyrek** [comment]
+1, how to get item name if I have classid.
I saw something like this in other bots:
var item = body.rgDescriptions[offer.items_to_receive[index].classid + '_' + offer.items_to_receive[index]..instanceid]
but rgDescriptions is not available in getOffers() function.

**Comment by srabouin** [comment]
http://api.steampowered.com/ISteamEconomy/GetAssetClassInfo/v0001/?classid0=211447708&class_count=1&appid=440&key=x

**Comment by Spyrek** [comment]
Thanks a lot!

**Comment by RakouskyS** [comment]
@srabouin thank you very much!
