### ISSUE TITLE
7 days trade ban bypass.

### ISSUE THREAD

**Issue by timaz0r** [Alex7Kom/node-steam-tradeoffers#87]
I saw some examples, there peoples want to use they ssfn files, or etc. to don't even wait new device trade ban. May I use this thing with node-steam-tradeoffers? And if yes, how?

**Comment by SuperDoker** [comment]
This is not a bug

**Comment by Alex7Kom** [comment]
This is not related to `steam-tradeoffers`.
See: https://github.com/seishun/node-steam/issues/106

**Comment by timaz0r** [comment]
Oh, so where I can found sentry file?
