### ISSUE TITLE
How would the bot communicate with a website?!

### ISSUE THREAD

**Issue by mikelsx** [Alex7Kom/node-steam-tradeoffers#90]
i got a bot set up, how can i send a request from my website telling the bot to send a trade offer to x asking for the items a,b,c,d?
do i need to use socket.io?
can you give me an example? my website is mostly in php.
Thanks in advance!

**Comment by MStruntze** [comment]
You can use NodeJS's built in "net" module along php's socket library: http://php.net/manual/en/sockets.examples.php

**Comment by mikelsx** [comment]
using node.js for calling the send trade offer from my website would be easier. i'd just have to pass 4 variables from php to node.js
any other way/tip?

**Comment by MStruntze** [comment]
Just pass the four variables from your php script through your socket connection to your nodejs bot and from there send the trade offer?

**Comment by mikelsx** [comment]
and how would i pass the variables from php to nodejs? can you give me an example?

**Comment by MStruntze** [comment]
You could use json_encode to encode your array of variables.
Refer to example 2 here: http://php.net/manual/en/sockets.examples.php for a php socket client example.
Here's an example on how to create a nodejs socket server: http://www.hacksparrow.com/tcp-socket-programming-in-node-js.html

**Comment by mikelsx** [comment]
uhmm. the php will be on my linux server, the bot will work on a windows 7 vps

**Comment by MStruntze** [comment]
Why don't you run it on the same server?
Anyway, I created an example for you:
https://gist.github.com/MStruntze/d7de3ea07b2777ca9f6d
I haven't tested it myself and you'll need to change it to fit your needs.

**Comment by mikelsx** [comment]
because i have no idea how i'll run node.js on linux lol. 
thanks for the example,ill check it out tomorrow but it looks good.
what about queuing the users? should i do it via php? like,check if the bot is in a trade or not?

**Comment by MStruntze** [comment]
You can have up to 30 ongoing trade offers per bot.
Either use socket comm to check if the bot is available or have another nodejs app that handles the trade offers delegation.

**Comment by Alex7Kom** [comment]
This is not related to `steam-tradeoffers`.
