### ISSUE TITLE
Would this work?

### ISSUE THREAD

**Issue by mikelsx** [Alex7Kom/node-steam-tradeoffers#91]
alright, so im planning on communicating with the bot from my website (eg, send a request to trade with X the item a, b, c ,d). The method im using seems pretty fishy for now, but meh.
i cant test the code as my main account (the only account i actually have atm) is 7days banned cuz of the bot, so can you take a quick look at this?

    Sock.on('data', function(data) {
	   requestno = requestno + 1
	   logger.info("#### Request number: " + requestno);
       dataobj = JSON.parse(data);
       item1 = dataobj.item1;
	   item2 = dataobj.item2;
	   item3 = dataobj.item3;
	   item4 = dataobj.item4;
	   steamid = dataobj.steamid;
	   console.log("");
       console.log('Item ID: ' + item1);
	   console.log('Item ID: ' + item2);
	   console.log('Item ID: ' + item3);
	   console.log('Item ID: ' + item4);
	   console.log('Steam ID: ' + steamid);
	   console.log("");
       console.log("Attempting to send trade-offer");
	   
		if (item1) {
          offers.makeOffer ({
            partnerSteamId: steamid,
            itemsFromMe: [
              {
                appid: 440,
                contextid: 2,
                amount: 1,
                assetid: item1,
				appid: 440,
                contextid: 2,
                amount: 1,
                assetid: item2,
				appid: 440,
                contextid: 2,
                amount: 1,
                assetid: item3,
				appid: 440,
                contextid: 2,
                amount: 1,
                assetid: item4
              }
            ],
            itemsFromThem: [],
            message: 'This is an automatic trade offer. This is just a test. '
          }, function(err, response){
            if (err) {
              logger.error(err);
            }
            logger.info(response);
			
          });
        }
		
      });

thanks!

**Comment by theahindle** [comment]
itemsFromMe should be an array of objects:
```
itemsFromMe: [
{
  .... item1
},
{
  .... item2
}.
{
  .... item3
}
```

**Comment by mikelsx** [comment]
ah, got it.
