### ISSUE TITLE
Error: There was an error sending your trade offer.  Please try again later. (26)

### ISSUE THREAD

**Issue by mantux5** [Alex7Kom/node-steam-tradeoffers#93]
I keep getting this error on some items. Other go through well. I suppose this might be STEAM related issue, but I need to be sure.

Any info about this error?

**Comment by l419351633** [comment]
Check your item object. I hope this will help you.

**Comment by blanko18** [comment]
Base on my experience this happens either when you try to bet an item that is already gone or your account has 5 more pending trade offers

**Comment by mantux5** [comment]
I know about this appearing with items which are not in the inventory. If you have reached limit, there is another error. But the problem is that, the item is in the inventory and even with 0 pending trade offers this error is given. I would understand that I made something wrong, but it works on some items, others simply do no not work :/

**Comment by bastienvans** [comment]
I've been getting the same error message for the last 24 hours. It works fine through Steam Community, but not through the Bot.

**Comment by bastienvans** [comment]
The bot has 0 pending trade offers.

**Comment by mantux5** [comment]
I found the issue, why I kept receiving this one. STEAM uses  64-bit integers as item ids, and some of these exceed 32-bit integer boundaries. And for some reason I converted them all to 32-bit integers. Now changed it to be as String as it does work well.

**Comment by bastienvans** [comment]
Thank you mantux5. It works for me as well.

**Comment by Duacz** [comment]
I have the same problem, I do not understand your statement as I have to convert to 32 bit integers,
32-bit and 64-bit the same number, but 32 have earlier boundaries
