### ISSUE TITLE
Declineoffer/getoffers returning no response/ not working

### ISSUE THREAD

**Issue by Clickplaycorp** [Alex7Kom/node-steam-tradeoffers#95]
hi can you verify if the declineoffer/getoffers functionality are still working?
when i try to use it the callback only returns this value

"response: {}"

thanks

**Comment by Alex7Kom** [comment]
Yes, they are still working.

**Comment by graycatfromspace** [comment]
I am getting this issue, offers get sent i call the offerid with this method and get the same response. Its spastic though and lets some through while not others.
