### ISSUE TITLE
Cancel/decline offer

### ISSUE THREAD

**Issue by blanko18** [Alex7Kom/node-steam-tradeoffers#96]
Hi i still cant decline/cancel the offers even though i followed the correct building of parameter

These are my code: where tradeofferidA -> is the tradeofferid

var params2 = {
tradeOfferId:tradeofferidA
}

offers[rows[0].bot_steam_id].declineOffer(params2, function (err, callback) {
if (err) 
{
console.log("Cancel offer ERROR: " + err);
}
else
{
if (Object.keys(callback).length > 0) 
{
console.log("Cancel offer with callback");
console.log(callback);

}
else
{
console.log("Callback error");
}
}
});

***************************************************************************************************
If i display the params2 via console.log it is displayed as something like this
{ tradeOfferId: '428073619' }

i already checked this issue:
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/85

Kindly help urgent

**Comment by l419351633** [comment]
If the tradeOfferId parameter is right, you may need to check the offer object. The method is absolutely working fine.

**Comment by blanko18** [comment]
thanks but i am using the same object when i use the getOffer method and it is working :(
