### ISSUE TITLE
[Feature Request/Question] How can a bot accept and send untradable games?

### ISSUE THREAD

**Issue by AceLewis** [Alex7Kom/node-steam-tradeoffers#98]
How can a bot accept and send untradable games, bots such as ones used on Dispenser.tf and other websites can send you the gift via a bot. How would the same be done via a bot? I know tradable games can easily be sent but I would also like to be able to send non-tradable games without waiting.

**Comment by Alex7Kom** [comment]
It is done through the Steam gifting system and has nothing to do with trade offers.
