### ISSUE TITLE
Error trade offer 26

### ISSUE THREAD

**Issue by Duacz** [Alex7Kom/node-steam-tradeoffers#99]
Hello,
I have a problem with the id of an item more than 32 bits. I have error with number 26.

Skins 32-bit well shipped, and 64 did not.

Example:
ID of an item can not send 2170314003
ID of an item can send 2141955401

Data of skins read from the database

**Comment by graycatfromspace** [comment]
error number 26 seems to happen when you have more than 5 trades open with the same person.

**Comment by srabouin** [comment]
don't use 64-bit integers, use them as strings.
